/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	certificates "github.com/fire833/morfic/pkg/apis/certificates"
	scheme "github.com/fire833/morfic/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CertificateSigningRequestListsGetter has a method to return a CertificateSigningRequestListInterface.
// A group's client should implement this interface.
type CertificateSigningRequestListsGetter interface {
	CertificateSigningRequestLists(namespace string) CertificateSigningRequestListInterface
}

// CertificateSigningRequestListInterface has methods to work with CertificateSigningRequestList resources.
type CertificateSigningRequestListInterface interface {
	Create(ctx context.Context, certificateSigningRequestList *certificates.CertificateSigningRequestList, opts v1.CreateOptions) (*certificates.CertificateSigningRequestList, error)
	Update(ctx context.Context, certificateSigningRequestList *certificates.CertificateSigningRequestList, opts v1.UpdateOptions) (*certificates.CertificateSigningRequestList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*certificates.CertificateSigningRequestList, error)
	List(ctx context.Context, opts v1.ListOptions) (*certificates.CertificateSigningRequestListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *certificates.CertificateSigningRequestList, err error)
	CertificateSigningRequestListExpansion
}

// certificateSigningRequestLists implements CertificateSigningRequestListInterface
type certificateSigningRequestLists struct {
	client rest.Interface
	ns     string
}

// newCertificateSigningRequestLists returns a CertificateSigningRequestLists
func newCertificateSigningRequestLists(c *CertificatesClient, namespace string) *certificateSigningRequestLists {
	return &certificateSigningRequestLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the certificateSigningRequestList, and returns the corresponding certificateSigningRequestList object, and an error if there is any.
func (c *certificateSigningRequestLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *certificates.CertificateSigningRequestList, err error) {
	result = &certificates.CertificateSigningRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CertificateSigningRequestLists that match those selectors.
func (c *certificateSigningRequestLists) List(ctx context.Context, opts v1.ListOptions) (result *certificates.CertificateSigningRequestListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &certificates.CertificateSigningRequestListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested certificateSigningRequestLists.
func (c *certificateSigningRequestLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a certificateSigningRequestList and creates it.  Returns the server's representation of the certificateSigningRequestList, and an error, if there is any.
func (c *certificateSigningRequestLists) Create(ctx context.Context, certificateSigningRequestList *certificates.CertificateSigningRequestList, opts v1.CreateOptions) (result *certificates.CertificateSigningRequestList, err error) {
	result = &certificates.CertificateSigningRequestList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certificateSigningRequestList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a certificateSigningRequestList and updates it. Returns the server's representation of the certificateSigningRequestList, and an error, if there is any.
func (c *certificateSigningRequestLists) Update(ctx context.Context, certificateSigningRequestList *certificates.CertificateSigningRequestList, opts v1.UpdateOptions) (result *certificates.CertificateSigningRequestList, err error) {
	result = &certificates.CertificateSigningRequestList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		Name(certificateSigningRequestList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certificateSigningRequestList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the certificateSigningRequestList and deletes it. Returns an error if one occurs.
func (c *certificateSigningRequestLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *certificateSigningRequestLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched certificateSigningRequestList.
func (c *certificateSigningRequestLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *certificates.CertificateSigningRequestList, err error) {
	result = &certificates.CertificateSigningRequestList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("certificatesigningrequestlists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
