/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by lister-gen. DO NOT EDIT.

package firewall

import (
	firewall "github.com/fire833/vroute/pkg/apis/firewall"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FirewallTableListLister helps list FirewallTableLists.
// All objects returned here must be treated as read-only.
type FirewallTableListLister interface {
	// List lists all FirewallTableLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*firewall.FirewallTableList, err error)
	// FirewallTableLists returns an object that can list and get FirewallTableLists.
	FirewallTableLists(namespace string) FirewallTableListNamespaceLister
	FirewallTableListListerExpansion
}

// firewallTableListLister implements the FirewallTableListLister interface.
type firewallTableListLister struct {
	indexer cache.Indexer
}

// NewFirewallTableListLister returns a new FirewallTableListLister.
func NewFirewallTableListLister(indexer cache.Indexer) FirewallTableListLister {
	return &firewallTableListLister{indexer: indexer}
}

// List lists all FirewallTableLists in the indexer.
func (s *firewallTableListLister) List(selector labels.Selector) (ret []*firewall.FirewallTableList, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*firewall.FirewallTableList))
	})
	return ret, err
}

// FirewallTableLists returns an object that can list and get FirewallTableLists.
func (s *firewallTableListLister) FirewallTableLists(namespace string) FirewallTableListNamespaceLister {
	return firewallTableListNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FirewallTableListNamespaceLister helps list and get FirewallTableLists.
// All objects returned here must be treated as read-only.
type FirewallTableListNamespaceLister interface {
	// List lists all FirewallTableLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*firewall.FirewallTableList, err error)
	// Get retrieves the FirewallTableList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*firewall.FirewallTableList, error)
	FirewallTableListNamespaceListerExpansion
}

// firewallTableListNamespaceLister implements the FirewallTableListNamespaceLister
// interface.
type firewallTableListNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FirewallTableLists in the indexer for a given namespace.
func (s firewallTableListNamespaceLister) List(selector labels.Selector) (ret []*firewall.FirewallTableList, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*firewall.FirewallTableList))
	})
	return ret, err
}

// Get retrieves the FirewallTableList from the indexer for a given namespace and name.
func (s firewallTableListNamespaceLister) Get(name string) (*firewall.FirewallTableList, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(firewall.Resource("firewalltablelist"), name)
	}
	return obj.(*firewall.FirewallTableList), nil
}
