/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by lister-gen. DO NOT EDIT.

package firewall

import (
	firewall "github.com/fire833/vroute/pkg/apis/firewall"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FirewallChainLister helps list FirewallChains.
// All objects returned here must be treated as read-only.
type FirewallChainLister interface {
	// List lists all FirewallChains in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*firewall.FirewallChain, err error)
	// FirewallChains returns an object that can list and get FirewallChains.
	FirewallChains(namespace string) FirewallChainNamespaceLister
	FirewallChainListerExpansion
}

// firewallChainLister implements the FirewallChainLister interface.
type firewallChainLister struct {
	indexer cache.Indexer
}

// NewFirewallChainLister returns a new FirewallChainLister.
func NewFirewallChainLister(indexer cache.Indexer) FirewallChainLister {
	return &firewallChainLister{indexer: indexer}
}

// List lists all FirewallChains in the indexer.
func (s *firewallChainLister) List(selector labels.Selector) (ret []*firewall.FirewallChain, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*firewall.FirewallChain))
	})
	return ret, err
}

// FirewallChains returns an object that can list and get FirewallChains.
func (s *firewallChainLister) FirewallChains(namespace string) FirewallChainNamespaceLister {
	return firewallChainNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FirewallChainNamespaceLister helps list and get FirewallChains.
// All objects returned here must be treated as read-only.
type FirewallChainNamespaceLister interface {
	// List lists all FirewallChains in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*firewall.FirewallChain, err error)
	// Get retrieves the FirewallChain from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*firewall.FirewallChain, error)
	FirewallChainNamespaceListerExpansion
}

// firewallChainNamespaceLister implements the FirewallChainNamespaceLister
// interface.
type firewallChainNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FirewallChains in the indexer for a given namespace.
func (s firewallChainNamespaceLister) List(selector labels.Selector) (ret []*firewall.FirewallChain, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*firewall.FirewallChain))
	})
	return ret, err
}

// Get retrieves the FirewallChain from the indexer for a given namespace and name.
func (s firewallChainNamespaceLister) Get(name string) (*firewall.FirewallChain, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(firewall.Resource("firewallchain"), name)
	}
	return obj.(*firewall.FirewallChain), nil
}
