/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	firewall "github.com/fire833/morfic/pkg/apis/firewall"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTables implements TableInterface
type FakeTables struct {
	Fake *FakeFirewall
	ns   string
}

var tablesResource = schema.GroupVersionResource{Group: "firewall.morfic.io", Version: "", Resource: "tables"}

var tablesKind = schema.GroupVersionKind{Group: "firewall.morfic.io", Version: "", Kind: "Table"}

// Get takes name of the table, and returns the corresponding table object, and an error if there is any.
func (c *FakeTables) Get(ctx context.Context, name string, options v1.GetOptions) (result *firewall.Table, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tablesResource, c.ns, name), &firewall.Table{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firewall.Table), err
}

// List takes label and field selectors, and returns the list of Tables that match those selectors.
func (c *FakeTables) List(ctx context.Context, opts v1.ListOptions) (result *firewall.TableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tablesResource, tablesKind, c.ns, opts), &firewall.TableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &firewall.TableList{ListMeta: obj.(*firewall.TableList).ListMeta}
	for _, item := range obj.(*firewall.TableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tables.
func (c *FakeTables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tablesResource, c.ns, opts))

}

// Create takes the representation of a table and creates it.  Returns the server's representation of the table, and an error, if there is any.
func (c *FakeTables) Create(ctx context.Context, table *firewall.Table, opts v1.CreateOptions) (result *firewall.Table, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tablesResource, c.ns, table), &firewall.Table{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firewall.Table), err
}

// Update takes the representation of a table and updates it. Returns the server's representation of the table, and an error, if there is any.
func (c *FakeTables) Update(ctx context.Context, table *firewall.Table, opts v1.UpdateOptions) (result *firewall.Table, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tablesResource, c.ns, table), &firewall.Table{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firewall.Table), err
}

// Delete takes name of the table and deletes it. Returns an error if one occurs.
func (c *FakeTables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(tablesResource, c.ns, name, opts), &firewall.Table{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tablesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &firewall.TableList{})
	return err
}

// Patch applies the patch and returns the patched table.
func (c *FakeTables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *firewall.Table, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tablesResource, c.ns, name, pt, data, subresources...), &firewall.Table{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firewall.Table), err
}
