/*
*	Copyright (C) 2023 Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by lister-gen. DO NOT EDIT.

package net

import (
	net "github.com/fire833/morfic/pkg/apis/net"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RouteTableListLister helps list RouteTableLists.
// All objects returned here must be treated as read-only.
type RouteTableListLister interface {
	// List lists all RouteTableLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*net.RouteTableList, err error)
	// Get retrieves the RouteTableList from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*net.RouteTableList, error)
	RouteTableListListerExpansion
}

// routeTableListLister implements the RouteTableListLister interface.
type routeTableListLister struct {
	indexer cache.Indexer
}

// NewRouteTableListLister returns a new RouteTableListLister.
func NewRouteTableListLister(indexer cache.Indexer) RouteTableListLister {
	return &routeTableListLister{indexer: indexer}
}

// List lists all RouteTableLists in the indexer.
func (s *routeTableListLister) List(selector labels.Selector) (ret []*net.RouteTableList, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*net.RouteTableList))
	})
	return ret, err
}

// Get retrieves the RouteTableList from the index for a given name.
func (s *routeTableListLister) Get(name string) (*net.RouteTableList, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(net.Resource("routetablelist"), name)
	}
	return obj.(*net.RouteTableList), nil
}
