/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by informer-gen. DO NOT EDIT.

package dns

import (
	internalinterfaces "pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DNSProviders returns a DNSProviderInformer.
	DNSProviders() DNSProviderInformer
	// DNSProviderLists returns a DNSProviderListInformer.
	DNSProviderLists() DNSProviderListInformer
	// DNSRecords returns a DNSRecordInformer.
	DNSRecords() DNSRecordInformer
	// DNSRecordLists returns a DNSRecordListInformer.
	DNSRecordLists() DNSRecordListInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DNSProviders returns a DNSProviderInformer.
func (v *version) DNSProviders() DNSProviderInformer {
	return &dNSProviderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSProviderLists returns a DNSProviderListInformer.
func (v *version) DNSProviderLists() DNSProviderListInformer {
	return &dNSProviderListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSRecords returns a DNSRecordInformer.
func (v *version) DNSRecords() DNSRecordInformer {
	return &dNSRecordInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSRecordLists returns a DNSRecordListInformer.
func (v *version) DNSRecordLists() DNSRecordListInformer {
	return &dNSRecordListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
