/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by informer-gen. DO NOT EDIT.

package certificates

import (
	"context"
	time "time"

	apiscertificates "github.com/fire833/morfic/pkg/apis/certificates"
	versioned "github.com/fire833/morfic/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fire833/morfic/pkg/client/informers/externalversions/internalinterfaces"
	certificates "github.com/fire833/morfic/pkg/client/listers/apis/certificates"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CertificateSigningRequestListInformer provides access to a shared informer and lister for
// CertificateSigningRequestLists.
type CertificateSigningRequestListInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() certificates.CertificateSigningRequestListLister
}

type certificateSigningRequestListInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCertificateSigningRequestListInformer constructs a new informer for CertificateSigningRequestList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCertificateSigningRequestListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCertificateSigningRequestListInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCertificateSigningRequestListInformer constructs a new informer for CertificateSigningRequestList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCertificateSigningRequestListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CertificatesCertificates().CertificateSigningRequestLists(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CertificatesCertificates().CertificateSigningRequestLists(namespace).Watch(context.TODO(), options)
			},
		},
		&apiscertificates.CertificateSigningRequestList{},
		resyncPeriod,
		indexers,
	)
}

func (f *certificateSigningRequestListInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCertificateSigningRequestListInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *certificateSigningRequestListInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscertificates.CertificateSigningRequestList{}, f.defaultInformer)
}

func (f *certificateSigningRequestListInformer) Lister() certificates.CertificateSigningRequestListLister {
	return certificates.NewCertificateSigningRequestListLister(f.Informer().GetIndexer())
}
