/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	net "github.com/fire833/morfic/pkg/apis/net"
	scheme "github.com/fire833/morfic/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AddressesGetter has a method to return a AddressInterface.
// A group's client should implement this interface.
type AddressesGetter interface {
	Addresses(namespace string) AddressInterface
}

// AddressInterface has methods to work with Address resources.
type AddressInterface interface {
	Create(ctx context.Context, address *net.Address, opts v1.CreateOptions) (*net.Address, error)
	Update(ctx context.Context, address *net.Address, opts v1.UpdateOptions) (*net.Address, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*net.Address, error)
	List(ctx context.Context, opts v1.ListOptions) (*net.AddressList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *net.Address, err error)
	AddressExpansion
}

// addresses implements AddressInterface
type addresses struct {
	client rest.Interface
	ns     string
}

// newAddresses returns a Addresses
func newAddresses(c *NetClient, namespace string) *addresses {
	return &addresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the address, and returns the corresponding address object, and an error if there is any.
func (c *addresses) Get(ctx context.Context, name string, options v1.GetOptions) (result *net.Address, err error) {
	result = &net.Address{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Addresses that match those selectors.
func (c *addresses) List(ctx context.Context, opts v1.ListOptions) (result *net.AddressList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &net.AddressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addresses.
func (c *addresses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("addresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a address and creates it.  Returns the server's representation of the address, and an error, if there is any.
func (c *addresses) Create(ctx context.Context, address *net.Address, opts v1.CreateOptions) (result *net.Address, err error) {
	result = &net.Address{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("addresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(address).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a address and updates it. Returns the server's representation of the address, and an error, if there is any.
func (c *addresses) Update(ctx context.Context, address *net.Address, opts v1.UpdateOptions) (result *net.Address, err error) {
	result = &net.Address{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addresses").
		Name(address.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(address).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the address and deletes it. Returns an error if one occurs.
func (c *addresses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addresses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addresses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addresses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched address.
func (c *addresses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *net.Address, err error) {
	result = &net.Address{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("addresses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
