/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	net "github.com/fire833/morfic/pkg/apis/net"
	scheme "github.com/fire833/morfic/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NeighborsGetter has a method to return a NeighborInterface.
// A group's client should implement this interface.
type NeighborsGetter interface {
	Neighbors(namespace string) NeighborInterface
}

// NeighborInterface has methods to work with Neighbor resources.
type NeighborInterface interface {
	Create(ctx context.Context, neighbor *net.Neighbor, opts v1.CreateOptions) (*net.Neighbor, error)
	Update(ctx context.Context, neighbor *net.Neighbor, opts v1.UpdateOptions) (*net.Neighbor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*net.Neighbor, error)
	List(ctx context.Context, opts v1.ListOptions) (*net.NeighborList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *net.Neighbor, err error)
	NeighborExpansion
}

// neighbors implements NeighborInterface
type neighbors struct {
	client rest.Interface
	ns     string
}

// newNeighbors returns a Neighbors
func newNeighbors(c *NetClient, namespace string) *neighbors {
	return &neighbors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the neighbor, and returns the corresponding neighbor object, and an error if there is any.
func (c *neighbors) Get(ctx context.Context, name string, options v1.GetOptions) (result *net.Neighbor, err error) {
	result = &net.Neighbor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("neighbors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Neighbors that match those selectors.
func (c *neighbors) List(ctx context.Context, opts v1.ListOptions) (result *net.NeighborList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &net.NeighborList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("neighbors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested neighbors.
func (c *neighbors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("neighbors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a neighbor and creates it.  Returns the server's representation of the neighbor, and an error, if there is any.
func (c *neighbors) Create(ctx context.Context, neighbor *net.Neighbor, opts v1.CreateOptions) (result *net.Neighbor, err error) {
	result = &net.Neighbor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("neighbors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(neighbor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a neighbor and updates it. Returns the server's representation of the neighbor, and an error, if there is any.
func (c *neighbors) Update(ctx context.Context, neighbor *net.Neighbor, opts v1.UpdateOptions) (result *net.Neighbor, err error) {
	result = &net.Neighbor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("neighbors").
		Name(neighbor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(neighbor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the neighbor and deletes it. Returns an error if one occurs.
func (c *neighbors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("neighbors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *neighbors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("neighbors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched neighbor.
func (c *neighbors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *net.Neighbor, err error) {
	result = &net.Neighbor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("neighbors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
