/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	dns "github.com/fire833/morfic/pkg/apis/dns"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSRecords implements DNSRecordInterface
type FakeDNSRecords struct {
	Fake *FakeDns
	ns   string
}

var dnsrecordsResource = schema.GroupVersionResource{Group: "dns.vroute.io", Version: "", Resource: "dnsrecords"}

var dnsrecordsKind = schema.GroupVersionKind{Group: "dns.vroute.io", Version: "", Kind: "DNSRecord"}

// Get takes name of the dNSRecord, and returns the corresponding dNSRecord object, and an error if there is any.
func (c *FakeDNSRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *dns.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnsrecordsResource, c.ns, name), &dns.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dns.DNSRecord), err
}

// List takes label and field selectors, and returns the list of DNSRecords that match those selectors.
func (c *FakeDNSRecords) List(ctx context.Context, opts v1.ListOptions) (result *dns.DNSRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnsrecordsResource, dnsrecordsKind, c.ns, opts), &dns.DNSRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dns.DNSRecordList{ListMeta: obj.(*dns.DNSRecordList).ListMeta}
	for _, item := range obj.(*dns.DNSRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSRecords.
func (c *FakeDNSRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnsrecordsResource, c.ns, opts))

}

// Create takes the representation of a dNSRecord and creates it.  Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Create(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.CreateOptions) (result *dns.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnsrecordsResource, c.ns, dNSRecord), &dns.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dns.DNSRecord), err
}

// Update takes the representation of a dNSRecord and updates it. Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Update(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.UpdateOptions) (result *dns.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnsrecordsResource, c.ns, dNSRecord), &dns.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dns.DNSRecord), err
}

// Delete takes name of the dNSRecord and deletes it. Returns an error if one occurs.
func (c *FakeDNSRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dnsrecordsResource, c.ns, name, opts), &dns.DNSRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnsrecordsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &dns.DNSRecordList{})
	return err
}

// Patch applies the patch and returns the patched dNSRecord.
func (c *FakeDNSRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dns.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnsrecordsResource, c.ns, name, pt, data, subresources...), &dns.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dns.DNSRecord), err
}
