/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CertificateListerExpansion allows custom methods to be added to
// CertificateLister.
type CertificateListerExpansion interface{}

// CertificateNamespaceListerExpansion allows custom methods to be added to
// CertificateNamespaceLister.
type CertificateNamespaceListerExpansion interface{}

// CertificateListListerExpansion allows custom methods to be added to
// CertificateListLister.
type CertificateListListerExpansion interface{}

// CertificateListNamespaceListerExpansion allows custom methods to be added to
// CertificateListNamespaceLister.
type CertificateListNamespaceListerExpansion interface{}

// CertificateSignerListerExpansion allows custom methods to be added to
// CertificateSignerLister.
type CertificateSignerListerExpansion interface{}

// CertificateSignerNamespaceListerExpansion allows custom methods to be added to
// CertificateSignerNamespaceLister.
type CertificateSignerNamespaceListerExpansion interface{}

// CertificateSignerListListerExpansion allows custom methods to be added to
// CertificateSignerListLister.
type CertificateSignerListListerExpansion interface{}

// CertificateSignerListNamespaceListerExpansion allows custom methods to be added to
// CertificateSignerListNamespaceLister.
type CertificateSignerListNamespaceListerExpansion interface{}

// CertificateSigningRequestListerExpansion allows custom methods to be added to
// CertificateSigningRequestLister.
type CertificateSigningRequestListerExpansion interface{}

// CertificateSigningRequestNamespaceListerExpansion allows custom methods to be added to
// CertificateSigningRequestNamespaceLister.
type CertificateSigningRequestNamespaceListerExpansion interface{}

// CertificateSigningRequestListListerExpansion allows custom methods to be added to
// CertificateSigningRequestListLister.
type CertificateSigningRequestListListerExpansion interface{}

// CertificateSigningRequestListNamespaceListerExpansion allows custom methods to be added to
// CertificateSigningRequestListNamespaceLister.
type CertificateSigningRequestListNamespaceListerExpansion interface{}
