/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	certificates "github.com/fire833/morfic/pkg/apis/certificates"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCertificateSignerLists implements CertificateSignerListInterface
type FakeCertificateSignerLists struct {
	Fake *FakeCertificates
	ns   string
}

var certificatesignerlistsResource = schema.GroupVersionResource{Group: "certificates.morfic.io", Version: "", Resource: "certificatesignerlists"}

var certificatesignerlistsKind = schema.GroupVersionKind{Group: "certificates.morfic.io", Version: "", Kind: "CertificateSignerList"}

// Get takes name of the certificateSignerList, and returns the corresponding certificateSignerList object, and an error if there is any.
func (c *FakeCertificateSignerLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *certificates.CertificateSignerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(certificatesignerlistsResource, c.ns, name), &certificates.CertificateSignerList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*certificates.CertificateSignerList), err
}

// List takes label and field selectors, and returns the list of CertificateSignerLists that match those selectors.
func (c *FakeCertificateSignerLists) List(ctx context.Context, opts v1.ListOptions) (result *certificates.CertificateSignerListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(certificatesignerlistsResource, certificatesignerlistsKind, c.ns, opts), &certificates.CertificateSignerListList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &certificates.CertificateSignerListList{ListMeta: obj.(*certificates.CertificateSignerListList).ListMeta}
	for _, item := range obj.(*certificates.CertificateSignerListList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested certificateSignerLists.
func (c *FakeCertificateSignerLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(certificatesignerlistsResource, c.ns, opts))

}

// Create takes the representation of a certificateSignerList and creates it.  Returns the server's representation of the certificateSignerList, and an error, if there is any.
func (c *FakeCertificateSignerLists) Create(ctx context.Context, certificateSignerList *certificates.CertificateSignerList, opts v1.CreateOptions) (result *certificates.CertificateSignerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(certificatesignerlistsResource, c.ns, certificateSignerList), &certificates.CertificateSignerList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*certificates.CertificateSignerList), err
}

// Update takes the representation of a certificateSignerList and updates it. Returns the server's representation of the certificateSignerList, and an error, if there is any.
func (c *FakeCertificateSignerLists) Update(ctx context.Context, certificateSignerList *certificates.CertificateSignerList, opts v1.UpdateOptions) (result *certificates.CertificateSignerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(certificatesignerlistsResource, c.ns, certificateSignerList), &certificates.CertificateSignerList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*certificates.CertificateSignerList), err
}

// Delete takes name of the certificateSignerList and deletes it. Returns an error if one occurs.
func (c *FakeCertificateSignerLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(certificatesignerlistsResource, c.ns, name, opts), &certificates.CertificateSignerList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCertificateSignerLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(certificatesignerlistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &certificates.CertificateSignerListList{})
	return err
}

// Patch applies the patch and returns the patched certificateSignerList.
func (c *FakeCertificateSignerLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *certificates.CertificateSignerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(certificatesignerlistsResource, c.ns, name, pt, data, subresources...), &certificates.CertificateSignerList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*certificates.CertificateSignerList), err
}
