// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_control.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReturnStatusCodes int32

const (
	// Default, action was successful and returned correct objects.
	ReturnStatusCodes_OK ReturnStatusCodes = 0
	// Request was accepted, but no response data yet/ever.
	ReturnStatusCodes_ACCEPTED ReturnStatusCodes = 1
	// Not allowed to create this element/perform operation.
	ReturnStatusCodes_PERMISSION_DENIED ReturnStatusCodes = 2
	// Element you are trying to interface with does not exist.
	ReturnStatusCodes_NOT_EXISTENT_ELEMENT ReturnStatusCodes = 3
	// Internal error with the server serving this request.
	ReturnStatusCodes_INTERNAL_ERROR ReturnStatusCodes = 4
	// Error in the request message syntax/format.
	ReturnStatusCodes_SYNTAX_ERROR ReturnStatusCodes = 5
	// No change in an update object, it was the same as original object.
	ReturnStatusCodes_NO_CHANGE_ERROR ReturnStatusCodes = 6
	// Returns if there is no object to return based on the given filter.
	ReturnStatusCodes_NO_FILTER_RESPONSE_ERROR ReturnStatusCodes = 7
	// Returns if there is an invalid field in the object
	ReturnStatusCodes_INVALID_FIELD_ERROR ReturnStatusCodes = 8
)

var ReturnStatusCodes_name = map[int32]string{
	0: "OK",
	1: "ACCEPTED",
	2: "PERMISSION_DENIED",
	3: "NOT_EXISTENT_ELEMENT",
	4: "INTERNAL_ERROR",
	5: "SYNTAX_ERROR",
	6: "NO_CHANGE_ERROR",
	7: "NO_FILTER_RESPONSE_ERROR",
	8: "INVALID_FIELD_ERROR",
}

var ReturnStatusCodes_value = map[string]int32{
	"OK":                       0,
	"ACCEPTED":                 1,
	"PERMISSION_DENIED":        2,
	"NOT_EXISTENT_ELEMENT":     3,
	"INTERNAL_ERROR":           4,
	"SYNTAX_ERROR":             5,
	"NO_CHANGE_ERROR":          6,
	"NO_FILTER_RESPONSE_ERROR": 7,
	"INVALID_FIELD_ERROR":      8,
}

func (x ReturnStatusCodes) String() string {
	return proto.EnumName(ReturnStatusCodes_name, int32(x))
}

func (ReturnStatusCodes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{0}
}

type LinkTypes int32

const (
	// This type is specified for those links that are defined by hardware device drivers,
	// not by users.
	LinkTypes_HARDWARE     LinkTypes = 0
	LinkTypes_VLAN         LinkTypes = 1
	LinkTypes_VETH         LinkTypes = 2
	LinkTypes_VCAN         LinkTypes = 3
	LinkTypes_VXCAN        LinkTypes = 4
	LinkTypes_DUMMY        LinkTypes = 5
	LinkTypes_IFB          LinkTypes = 6
	LinkTypes_MACVLAN      LinkTypes = 7
	LinkTypes_MACVTAP      LinkTypes = 8
	LinkTypes_BRIDGE       LinkTypes = 9
	LinkTypes_BOND         LinkTypes = 10
	LinkTypes_TEAM         LinkTypes = 11
	LinkTypes_IPOIB        LinkTypes = 12
	LinkTypes_IP6TNL       LinkTypes = 13
	LinkTypes_IPIP         LinkTypes = 14
	LinkTypes_SIT          LinkTypes = 15
	LinkTypes_VXLAN        LinkTypes = 16
	LinkTypes_GRE          LinkTypes = 17
	LinkTypes_GRETAP       LinkTypes = 18
	LinkTypes_ERSPAN       LinkTypes = 19
	LinkTypes_IP6GRE       LinkTypes = 20
	LinkTypes_IP6GRETAP    LinkTypes = 21
	LinkTypes_IP6ERSPAN    LinkTypes = 22
	LinkTypes_VTI          LinkTypes = 23
	LinkTypes_NLMON        LinkTypes = 24
	LinkTypes_TEAM_SLAVE   LinkTypes = 25
	LinkTypes_BOND_SLAVE   LinkTypes = 26
	LinkTypes_BRIDGE_SLAVE LinkTypes = 27
	LinkTypes_IPVLAN       LinkTypes = 28
	LinkTypes_IPVTAP       LinkTypes = 29
	LinkTypes_GENEVE       LinkTypes = 30
	LinkTypes_VRF          LinkTypes = 31
	LinkTypes_MACSEC       LinkTypes = 32
	LinkTypes_NETDEVSIM    LinkTypes = 33
	LinkTypes_RMNET        LinkTypes = 34
)

var LinkTypes_name = map[int32]string{
	0:  "HARDWARE",
	1:  "VLAN",
	2:  "VETH",
	3:  "VCAN",
	4:  "VXCAN",
	5:  "DUMMY",
	6:  "IFB",
	7:  "MACVLAN",
	8:  "MACVTAP",
	9:  "BRIDGE",
	10: "BOND",
	11: "TEAM",
	12: "IPOIB",
	13: "IP6TNL",
	14: "IPIP",
	15: "SIT",
	16: "VXLAN",
	17: "GRE",
	18: "GRETAP",
	19: "ERSPAN",
	20: "IP6GRE",
	21: "IP6GRETAP",
	22: "IP6ERSPAN",
	23: "VTI",
	24: "NLMON",
	25: "TEAM_SLAVE",
	26: "BOND_SLAVE",
	27: "BRIDGE_SLAVE",
	28: "IPVLAN",
	29: "IPVTAP",
	30: "GENEVE",
	31: "VRF",
	32: "MACSEC",
	33: "NETDEVSIM",
	34: "RMNET",
}

var LinkTypes_value = map[string]int32{
	"HARDWARE":     0,
	"VLAN":         1,
	"VETH":         2,
	"VCAN":         3,
	"VXCAN":        4,
	"DUMMY":        5,
	"IFB":          6,
	"MACVLAN":      7,
	"MACVTAP":      8,
	"BRIDGE":       9,
	"BOND":         10,
	"TEAM":         11,
	"IPOIB":        12,
	"IP6TNL":       13,
	"IPIP":         14,
	"SIT":          15,
	"VXLAN":        16,
	"GRE":          17,
	"GRETAP":       18,
	"ERSPAN":       19,
	"IP6GRE":       20,
	"IP6GRETAP":    21,
	"IP6ERSPAN":    22,
	"VTI":          23,
	"NLMON":        24,
	"TEAM_SLAVE":   25,
	"BOND_SLAVE":   26,
	"BRIDGE_SLAVE": 27,
	"IPVLAN":       28,
	"IPVTAP":       29,
	"GENEVE":       30,
	"VRF":          31,
	"MACSEC":       32,
	"NETDEVSIM":    33,
	"RMNET":        34,
}

func (x LinkTypes) String() string {
	return proto.EnumName(LinkTypes_name, int32(x))
}

func (LinkTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{1}
}

type LinkElements int32

const (
	LinkElements_NAME       LinkElements = 0
	LinkElements_ADDRESS    LinkElements = 1
	LinkElements_MACADDRESS LinkElements = 2
	LinkElements_TYPE       LinkElements = 3
	LinkElements_MTU        LinkElements = 4
	LinkElements_INDEX      LinkElements = 5
)

var LinkElements_name = map[int32]string{
	0: "NAME",
	1: "ADDRESS",
	2: "MACADDRESS",
	3: "TYPE",
	4: "MTU",
	5: "INDEX",
}

var LinkElements_value = map[string]int32{
	"NAME":       0,
	"ADDRESS":    1,
	"MACADDRESS": 2,
	"TYPE":       3,
	"MTU":        4,
	"INDEX":      5,
}

func (x LinkElements) String() string {
	return proto.EnumName(LinkElements_name, int32(x))
}

func (LinkElements) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{2}
}

// Used for GET operations, and allows specification
// of the elements that the user wants to filter by.
type RouteElements int32

const (
	RouteElements_DESTINATION RouteElements = 0
	RouteElements_GATEWAY     RouteElements = 1
	RouteElements_METRIC      RouteElements = 2
	RouteElements_INTERFACE   RouteElements = 3
)

var RouteElements_name = map[int32]string{
	0: "DESTINATION",
	1: "GATEWAY",
	2: "METRIC",
	3: "INTERFACE",
}

var RouteElements_value = map[string]int32{
	"DESTINATION": 0,
	"GATEWAY":     1,
	"METRIC":      2,
	"INTERFACE":   3,
}

func (x RouteElements) String() string {
	return proto.EnumName(RouteElements_name, int32(x))
}

func (RouteElements) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{3}
}

type IPType int32

const (
	IPType_IPV4 IPType = 0
	IPType_IPV6 IPType = 1
)

var IPType_name = map[int32]string{
	0: "IPV4",
	1: "IPV6",
}

var IPType_value = map[string]int32{
	"IPV4": 0,
	"IPV6": 1,
}

func (x IPType) String() string {
	return proto.EnumName(IPType_name, int32(x))
}

func (IPType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{4}
}

type LinkAddressAssignment int32

const (
	LinkAddressAssignment_STATIC LinkAddressAssignment = 0
	LinkAddressAssignment_DHCP   LinkAddressAssignment = 1
	LinkAddressAssignment_L2TP   LinkAddressAssignment = 2
)

var LinkAddressAssignment_name = map[int32]string{
	0: "STATIC",
	1: "DHCP",
	2: "L2TP",
}

var LinkAddressAssignment_value = map[string]int32{
	"STATIC": 0,
	"DHCP":   1,
	"L2TP":   2,
}

func (x LinkAddressAssignment) String() string {
	return proto.EnumName(LinkAddressAssignment_name, int32(x))
}

func (LinkAddressAssignment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{5}
}

type LinkMACAddressAssignment int32

const (
	// Use the defined hardware mac address that may come with whatever link
	// you are attaching this address object to.
	LinkMACAddressAssignment_HW LinkMACAddressAssignment = 0
	// Use a randomly generated mac address for this link.
	LinkMACAddressAssignment_RANDOM LinkMACAddressAssignment = 1
	// Link stays static, but was randomly generated.
	LinkMACAddressAssignment_STATIC_RANDOM LinkMACAddressAssignment = 2
	// User defines the address of this link's hardware address.
	LinkMACAddressAssignment_PREDEFINED LinkMACAddressAssignment = 3
)

var LinkMACAddressAssignment_name = map[int32]string{
	0: "HW",
	1: "RANDOM",
	2: "STATIC_RANDOM",
	3: "PREDEFINED",
}

var LinkMACAddressAssignment_value = map[string]int32{
	"HW":            0,
	"RANDOM":        1,
	"STATIC_RANDOM": 2,
	"PREDEFINED":    3,
}

func (x LinkMACAddressAssignment) String() string {
	return proto.EnumName(LinkMACAddressAssignment_name, int32(x))
}

func (LinkMACAddressAssignment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{6}
}

type NeighborElements int32

const (
	NeighborElements_IPTYPE    NeighborElements = 0
	NeighborElements_IPADDRESS NeighborElements = 1
	NeighborElements_MACADDR   NeighborElements = 2
	NeighborElements_STATE     NeighborElements = 3
)

var NeighborElements_name = map[int32]string{
	0: "IPTYPE",
	1: "IPADDRESS",
	2: "MACADDR",
	3: "STATE",
}

var NeighborElements_value = map[string]int32{
	"IPTYPE":    0,
	"IPADDRESS": 1,
	"MACADDR":   2,
	"STATE":     3,
}

func (x NeighborElements) String() string {
	return proto.EnumName(NeighborElements_name, int32(x))
}

func (NeighborElements) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{7}
}

type NeighborState int32

const (
	NeighborState_PERMANENT  NeighborState = 0
	NeighborState_NOARP      NeighborState = 1
	NeighborState_STALE      NeighborState = 2
	NeighborState_REACHABLE  NeighborState = 3
	NeighborState_NONE       NeighborState = 5
	NeighborState_INCOMPLETE NeighborState = 6
	NeighborState_DELAY      NeighborState = 7
	NeighborState_PROBE      NeighborState = 8
	NeighborState_FAILED     NeighborState = 9
)

var NeighborState_name = map[int32]string{
	0: "PERMANENT",
	1: "NOARP",
	2: "STALE",
	3: "REACHABLE",
	5: "NONE",
	6: "INCOMPLETE",
	7: "DELAY",
	8: "PROBE",
	9: "FAILED",
}

var NeighborState_value = map[string]int32{
	"PERMANENT":  0,
	"NOARP":      1,
	"STALE":      2,
	"REACHABLE":  3,
	"NONE":       5,
	"INCOMPLETE": 6,
	"DELAY":      7,
	"PROBE":      8,
	"FAILED":     9,
}

func (x NeighborState) String() string {
	return proto.EnumName(NeighborState_name, int32(x))
}

func (NeighborState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{8}
}

type CreateLinkRequest struct {
	// Describes multiple or one link that should be created with this request.
	Link                 []*Link  `protobuf:"bytes,1,rep,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkRequest) Reset()         { *m = CreateLinkRequest{} }
func (m *CreateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLinkRequest) ProtoMessage()    {}
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{0}
}

func (m *CreateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkRequest.Unmarshal(m, b)
}
func (m *CreateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkRequest.Marshal(b, m, deterministic)
}
func (m *CreateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkRequest.Merge(m, src)
}
func (m *CreateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLinkRequest.Size(m)
}
func (m *CreateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkRequest proto.InternalMessageInfo

func (m *CreateLinkRequest) GetLink() []*Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type CreateLinkResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this link schema.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Links that were created successfully.
	SuccessLinks []*Link `protobuf:"bytes,3,rep,name=success_links,json=successLinks,proto3" json:"success_links,omitempty"`
	// Links that were created unsuccessfully.
	UnsuccessfulLinks    []*Link  `protobuf:"bytes,4,rep,name=unsuccessful_links,json=unsuccessfulLinks,proto3" json:"unsuccessful_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkResponse) Reset()         { *m = CreateLinkResponse{} }
func (m *CreateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLinkResponse) ProtoMessage()    {}
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{1}
}

func (m *CreateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkResponse.Unmarshal(m, b)
}
func (m *CreateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkResponse.Marshal(b, m, deterministic)
}
func (m *CreateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkResponse.Merge(m, src)
}
func (m *CreateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLinkResponse.Size(m)
}
func (m *CreateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkResponse proto.InternalMessageInfo

func (m *CreateLinkResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *CreateLinkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateLinkResponse) GetSuccessLinks() []*Link {
	if m != nil {
		return m.SuccessLinks
	}
	return nil
}

func (m *CreateLinkResponse) GetUnsuccessfulLinks() []*Link {
	if m != nil {
		return m.UnsuccessfulLinks
	}
	return nil
}

type UpdateLinkRequest struct {
	// The name of the link
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link                 *Link    `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkRequest) Reset()         { *m = UpdateLinkRequest{} }
func (m *UpdateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkRequest) ProtoMessage()    {}
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{2}
}

func (m *UpdateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkRequest.Unmarshal(m, b)
}
func (m *UpdateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkRequest.Merge(m, src)
}
func (m *UpdateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkRequest.Size(m)
}
func (m *UpdateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkRequest proto.InternalMessageInfo

func (m *UpdateLinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateLinkRequest) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type UpdateLinkResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this link schema.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkResponse) Reset()         { *m = UpdateLinkResponse{} }
func (m *UpdateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkResponse) ProtoMessage()    {}
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{3}
}

func (m *UpdateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkResponse.Unmarshal(m, b)
}
func (m *UpdateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkResponse.Merge(m, src)
}
func (m *UpdateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkResponse.Size(m)
}
func (m *UpdateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkResponse proto.InternalMessageInfo

func (m *UpdateLinkResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *UpdateLinkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteLinkRequest struct {
	// Delete one or more links.
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkRequest) Reset()         { *m = DeleteLinkRequest{} }
func (m *DeleteLinkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkRequest) ProtoMessage()    {}
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{4}
}

func (m *DeleteLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkRequest.Unmarshal(m, b)
}
func (m *DeleteLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkRequest.Merge(m, src)
}
func (m *DeleteLinkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkRequest.Size(m)
}
func (m *DeleteLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkRequest proto.InternalMessageInfo

func (m *DeleteLinkRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type DeleteLinkResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Returns the deleted links that were removed
	// from the kernel with this request.
	DeletedLinks         []*Link  `protobuf:"bytes,2,rep,name=deleted_links,json=deletedLinks,proto3" json:"deleted_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkResponse) Reset()         { *m = DeleteLinkResponse{} }
func (m *DeleteLinkResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkResponse) ProtoMessage()    {}
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{5}
}

func (m *DeleteLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkResponse.Unmarshal(m, b)
}
func (m *DeleteLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkResponse.Merge(m, src)
}
func (m *DeleteLinkResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkResponse.Size(m)
}
func (m *DeleteLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkResponse proto.InternalMessageInfo

func (m *DeleteLinkResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *DeleteLinkResponse) GetDeletedLinks() []*Link {
	if m != nil {
		return m.DeletedLinks
	}
	return nil
}

type GetLinkRequest struct {
	// Specify the elements that you want to sort by.
	FilterElems map[string]string `protobuf:"bytes,1,rep,name=filter_elems,json=filterElems,proto3" json:"filter_elems,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Specify the maximum number of links/interfaces that you want back.
	MaxLinks             int32    `protobuf:"varint,2,opt,name=max_links,json=maxLinks,proto3" json:"max_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinkRequest) Reset()         { *m = GetLinkRequest{} }
func (m *GetLinkRequest) String() string { return proto.CompactTextString(m) }
func (*GetLinkRequest) ProtoMessage()    {}
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{6}
}

func (m *GetLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinkRequest.Unmarshal(m, b)
}
func (m *GetLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinkRequest.Marshal(b, m, deterministic)
}
func (m *GetLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinkRequest.Merge(m, src)
}
func (m *GetLinkRequest) XXX_Size() int {
	return xxx_messageInfo_GetLinkRequest.Size(m)
}
func (m *GetLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinkRequest proto.InternalMessageInfo

func (m *GetLinkRequest) GetFilterElems() map[string]string {
	if m != nil {
		return m.FilterElems
	}
	return nil
}

func (m *GetLinkRequest) GetMaxLinks() int32 {
	if m != nil {
		return m.MaxLinks
	}
	return 0
}

type GetLinkResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error string if there was any getting kernel links.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the link objects that are on the host.
	Links                []*Link  `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinkResponse) Reset()         { *m = GetLinkResponse{} }
func (m *GetLinkResponse) String() string { return proto.CompactTextString(m) }
func (*GetLinkResponse) ProtoMessage()    {}
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{7}
}

func (m *GetLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinkResponse.Unmarshal(m, b)
}
func (m *GetLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinkResponse.Marshal(b, m, deterministic)
}
func (m *GetLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinkResponse.Merge(m, src)
}
func (m *GetLinkResponse) XXX_Size() int {
	return xxx_messageInfo_GetLinkResponse.Size(m)
}
func (m *GetLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinkResponse proto.InternalMessageInfo

func (m *GetLinkResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetLinkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetLinkResponse) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

type GetAllLinksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllLinksRequest) Reset()         { *m = GetAllLinksRequest{} }
func (m *GetAllLinksRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllLinksRequest) ProtoMessage()    {}
func (*GetAllLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{8}
}

func (m *GetAllLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllLinksRequest.Unmarshal(m, b)
}
func (m *GetAllLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllLinksRequest.Marshal(b, m, deterministic)
}
func (m *GetAllLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllLinksRequest.Merge(m, src)
}
func (m *GetAllLinksRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllLinksRequest.Size(m)
}
func (m *GetAllLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllLinksRequest proto.InternalMessageInfo

type GetAllLinksResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error string if there was any getting kernel interfaces.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the interface objects that are on the host.
	Links                []*Link  `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllLinksResponse) Reset()         { *m = GetAllLinksResponse{} }
func (m *GetAllLinksResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllLinksResponse) ProtoMessage()    {}
func (*GetAllLinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{9}
}

func (m *GetAllLinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllLinksResponse.Unmarshal(m, b)
}
func (m *GetAllLinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllLinksResponse.Marshal(b, m, deterministic)
}
func (m *GetAllLinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllLinksResponse.Merge(m, src)
}
func (m *GetAllLinksResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllLinksResponse.Size(m)
}
func (m *GetAllLinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllLinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllLinksResponse proto.InternalMessageInfo

func (m *GetAllLinksResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetAllLinksResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetAllLinksResponse) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

type Link struct {
	// Describes the interface address for this link.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Addressing for this link
	Address []*LinkAddress `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	// MAC hardware addressing for this link
	Mac *LinkMACAddress `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	// The type of this link.
	Type LinkTypes `protobuf:"varint,4,opt,name=type,proto3,enum=v1alpha1.LinkTypes" json:"type,omitempty"`
	// MTU of link.
	Mtu uint32 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Specify the index of the link
	Index                uint32          `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Attributes           *LinkAttributes `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{10}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Link) GetAddress() []*LinkAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Link) GetMac() *LinkMACAddress {
	if m != nil {
		return m.Mac
	}
	return nil
}

func (m *Link) GetType() LinkTypes {
	if m != nil {
		return m.Type
	}
	return LinkTypes_HARDWARE
}

func (m *Link) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Link) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Link) GetAttributes() *LinkAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Attributes for a link.
type LinkAttributes struct {
	// Is the link up.
	Up bool `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	// Is arp handling enabled on the link.
	ArpEnabled           bool     `protobuf:"varint,2,opt,name=arp_enabled,json=arpEnabled,proto3" json:"arp_enabled,omitempty"`
	Dynamic              bool     `protobuf:"varint,3,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	Multicast            bool     `protobuf:"varint,4,opt,name=multicast,proto3" json:"multicast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkAttributes) Reset()         { *m = LinkAttributes{} }
func (m *LinkAttributes) String() string { return proto.CompactTextString(m) }
func (*LinkAttributes) ProtoMessage()    {}
func (*LinkAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{11}
}

func (m *LinkAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkAttributes.Unmarshal(m, b)
}
func (m *LinkAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkAttributes.Marshal(b, m, deterministic)
}
func (m *LinkAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkAttributes.Merge(m, src)
}
func (m *LinkAttributes) XXX_Size() int {
	return xxx_messageInfo_LinkAttributes.Size(m)
}
func (m *LinkAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_LinkAttributes proto.InternalMessageInfo

func (m *LinkAttributes) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

func (m *LinkAttributes) GetArpEnabled() bool {
	if m != nil {
		return m.ArpEnabled
	}
	return false
}

func (m *LinkAttributes) GetDynamic() bool {
	if m != nil {
		return m.Dynamic
	}
	return false
}

func (m *LinkAttributes) GetMulticast() bool {
	if m != nil {
		return m.Multicast
	}
	return false
}

type GetRouteRequest struct {
	// Specify the elements that you want to sort by.
	FilterElems map[string]string `protobuf:"bytes,1,rep,name=filter_elems,json=filterElems,proto3" json:"filter_elems,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Specify the maximum number of routes that you want back.
	MaxRoutes            int32    `protobuf:"varint,2,opt,name=max_routes,json=maxRoutes,proto3" json:"max_routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRouteRequest) Reset()         { *m = GetRouteRequest{} }
func (m *GetRouteRequest) String() string { return proto.CompactTextString(m) }
func (*GetRouteRequest) ProtoMessage()    {}
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{12}
}

func (m *GetRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRouteRequest.Unmarshal(m, b)
}
func (m *GetRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRouteRequest.Marshal(b, m, deterministic)
}
func (m *GetRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRouteRequest.Merge(m, src)
}
func (m *GetRouteRequest) XXX_Size() int {
	return xxx_messageInfo_GetRouteRequest.Size(m)
}
func (m *GetRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRouteRequest proto.InternalMessageInfo

func (m *GetRouteRequest) GetFilterElems() map[string]string {
	if m != nil {
		return m.FilterElems
	}
	return nil
}

func (m *GetRouteRequest) GetMaxRoutes() int32 {
	if m != nil {
		return m.MaxRoutes
	}
	return 0
}

type GetRouteResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error string if there was any getting kernel routes.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the route objects that are on the host.
	Route                *Route   `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRouteResponse) Reset()         { *m = GetRouteResponse{} }
func (m *GetRouteResponse) String() string { return proto.CompactTextString(m) }
func (*GetRouteResponse) ProtoMessage()    {}
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{13}
}

func (m *GetRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRouteResponse.Unmarshal(m, b)
}
func (m *GetRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRouteResponse.Marshal(b, m, deterministic)
}
func (m *GetRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRouteResponse.Merge(m, src)
}
func (m *GetRouteResponse) XXX_Size() int {
	return xxx_messageInfo_GetRouteResponse.Size(m)
}
func (m *GetRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRouteResponse proto.InternalMessageInfo

func (m *GetRouteResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetRouteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetRouteResponse) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type GetAllRoutesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRoutesRequest) Reset()         { *m = GetAllRoutesRequest{} }
func (m *GetAllRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRoutesRequest) ProtoMessage()    {}
func (*GetAllRoutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{14}
}

func (m *GetAllRoutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRoutesRequest.Unmarshal(m, b)
}
func (m *GetAllRoutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRoutesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRoutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRoutesRequest.Merge(m, src)
}
func (m *GetAllRoutesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRoutesRequest.Size(m)
}
func (m *GetAllRoutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRoutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRoutesRequest proto.InternalMessageInfo

type GetAllRoutesResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error string if there was any getting kernel routes.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the route objects that are on the host.
	Routes               *Route   `protobuf:"bytes,3,opt,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRoutesResponse) Reset()         { *m = GetAllRoutesResponse{} }
func (m *GetAllRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllRoutesResponse) ProtoMessage()    {}
func (*GetAllRoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{15}
}

func (m *GetAllRoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRoutesResponse.Unmarshal(m, b)
}
func (m *GetAllRoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRoutesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllRoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRoutesResponse.Merge(m, src)
}
func (m *GetAllRoutesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllRoutesResponse.Size(m)
}
func (m *GetAllRoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRoutesResponse proto.InternalMessageInfo

func (m *GetAllRoutesResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetAllRoutesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetAllRoutesResponse) GetRoutes() *Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type CreateStaticRouteRequest struct {
	// Can create one or multiple routes with a single request.
	Route                []*Route `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStaticRouteRequest) Reset()         { *m = CreateStaticRouteRequest{} }
func (m *CreateStaticRouteRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStaticRouteRequest) ProtoMessage()    {}
func (*CreateStaticRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{16}
}

func (m *CreateStaticRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStaticRouteRequest.Unmarshal(m, b)
}
func (m *CreateStaticRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStaticRouteRequest.Marshal(b, m, deterministic)
}
func (m *CreateStaticRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStaticRouteRequest.Merge(m, src)
}
func (m *CreateStaticRouteRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStaticRouteRequest.Size(m)
}
func (m *CreateStaticRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStaticRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStaticRouteRequest proto.InternalMessageInfo

func (m *CreateStaticRouteRequest) GetRoute() []*Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type CreateStaticRouteResponse struct {
	// Return the response status for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error string if there was adding the routes.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the routes that failed to be created.
	FailedRoutes         []*Route `protobuf:"bytes,3,rep,name=failed_routes,json=failedRoutes,proto3" json:"failed_routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStaticRouteResponse) Reset()         { *m = CreateStaticRouteResponse{} }
func (m *CreateStaticRouteResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStaticRouteResponse) ProtoMessage()    {}
func (*CreateStaticRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{17}
}

func (m *CreateStaticRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStaticRouteResponse.Unmarshal(m, b)
}
func (m *CreateStaticRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStaticRouteResponse.Marshal(b, m, deterministic)
}
func (m *CreateStaticRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStaticRouteResponse.Merge(m, src)
}
func (m *CreateStaticRouteResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStaticRouteResponse.Size(m)
}
func (m *CreateStaticRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStaticRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStaticRouteResponse proto.InternalMessageInfo

func (m *CreateStaticRouteResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *CreateStaticRouteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateStaticRouteResponse) GetFailedRoutes() []*Route {
	if m != nil {
		return m.FailedRoutes
	}
	return nil
}

type DeleteStaticRouteRequest struct {
	Route                []*Route `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStaticRouteRequest) Reset()         { *m = DeleteStaticRouteRequest{} }
func (m *DeleteStaticRouteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStaticRouteRequest) ProtoMessage()    {}
func (*DeleteStaticRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{18}
}

func (m *DeleteStaticRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStaticRouteRequest.Unmarshal(m, b)
}
func (m *DeleteStaticRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStaticRouteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStaticRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStaticRouteRequest.Merge(m, src)
}
func (m *DeleteStaticRouteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStaticRouteRequest.Size(m)
}
func (m *DeleteStaticRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStaticRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStaticRouteRequest proto.InternalMessageInfo

func (m *DeleteStaticRouteRequest) GetRoute() []*Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type DeleteStaticRouteResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this route schema.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Returns the route struct that was removed from the kernel.
	Route                []*Route `protobuf:"bytes,3,rep,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStaticRouteResponse) Reset()         { *m = DeleteStaticRouteResponse{} }
func (m *DeleteStaticRouteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStaticRouteResponse) ProtoMessage()    {}
func (*DeleteStaticRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{19}
}

func (m *DeleteStaticRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStaticRouteResponse.Unmarshal(m, b)
}
func (m *DeleteStaticRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStaticRouteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStaticRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStaticRouteResponse.Merge(m, src)
}
func (m *DeleteStaticRouteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStaticRouteResponse.Size(m)
}
func (m *DeleteStaticRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStaticRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStaticRouteResponse proto.InternalMessageInfo

func (m *DeleteStaticRouteResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *DeleteStaticRouteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteStaticRouteResponse) GetRoute() []*Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type UpdateStaticRouteRequest struct {
	// string name = 1;
	// Specify the new object that will be compared and override the old.
	Route                *Route   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStaticRouteRequest) Reset()         { *m = UpdateStaticRouteRequest{} }
func (m *UpdateStaticRouteRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStaticRouteRequest) ProtoMessage()    {}
func (*UpdateStaticRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{20}
}

func (m *UpdateStaticRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStaticRouteRequest.Unmarshal(m, b)
}
func (m *UpdateStaticRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStaticRouteRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStaticRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStaticRouteRequest.Merge(m, src)
}
func (m *UpdateStaticRouteRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStaticRouteRequest.Size(m)
}
func (m *UpdateStaticRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStaticRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStaticRouteRequest proto.InternalMessageInfo

func (m *UpdateStaticRouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type UpdateStaticRouteResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this route schema.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStaticRouteResponse) Reset()         { *m = UpdateStaticRouteResponse{} }
func (m *UpdateStaticRouteResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStaticRouteResponse) ProtoMessage()    {}
func (*UpdateStaticRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{21}
}

func (m *UpdateStaticRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStaticRouteResponse.Unmarshal(m, b)
}
func (m *UpdateStaticRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStaticRouteResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStaticRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStaticRouteResponse.Merge(m, src)
}
func (m *UpdateStaticRouteResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStaticRouteResponse.Size(m)
}
func (m *UpdateStaticRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStaticRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStaticRouteResponse proto.InternalMessageInfo

func (m *UpdateStaticRouteResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *UpdateStaticRouteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Describes a route object to be managed with this service.
type Route struct {
	// Describes the destination range for the route.
	Destination *IPCIDR `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Gateway IP address for this route.
	Gateway *IPAddress `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Cost metric for this route.
	Metric int32 `protobuf:"varint,4,opt,name=metric,proto3" json:"metric,omitempty"`
	// Name of outbound interface for routes.
	Interface            string   `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{22}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetDestination() *IPCIDR {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Route) GetGateway() *IPAddress {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *Route) GetMetric() int32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *Route) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type IPCIDR struct {
	Address              *IPAddress `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mask                 *IPMask    `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IPCIDR) Reset()         { *m = IPCIDR{} }
func (m *IPCIDR) String() string { return proto.CompactTextString(m) }
func (*IPCIDR) ProtoMessage()    {}
func (*IPCIDR) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{23}
}

func (m *IPCIDR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPCIDR.Unmarshal(m, b)
}
func (m *IPCIDR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPCIDR.Marshal(b, m, deterministic)
}
func (m *IPCIDR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPCIDR.Merge(m, src)
}
func (m *IPCIDR) XXX_Size() int {
	return xxx_messageInfo_IPCIDR.Size(m)
}
func (m *IPCIDR) XXX_DiscardUnknown() {
	xxx_messageInfo_IPCIDR.DiscardUnknown(m)
}

var xxx_messageInfo_IPCIDR proto.InternalMessageInfo

func (m *IPCIDR) GetAddress() *IPAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *IPCIDR) GetMask() *IPMask {
	if m != nil {
		return m.Mask
	}
	return nil
}

type IPMask struct {
	// Specify the type of this mask.
	Type IPType `protobuf:"varint,1,opt,name=type,proto3,enum=v1alpha1.IPType" json:"type,omitempty"`
	// Specification of the number of 1s in the subnet mask for this address.
	//
	// An example is a /24 network or 255.255.255.0 subnet mask would be valued as 24.
	// Same with 255.0.0.0 or /8 network would be 8.
	//
	// The same thing applies for IPv6 addresses.
	Mask                 uint32   `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPMask) Reset()         { *m = IPMask{} }
func (m *IPMask) String() string { return proto.CompactTextString(m) }
func (*IPMask) ProtoMessage()    {}
func (*IPMask) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{24}
}

func (m *IPMask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPMask.Unmarshal(m, b)
}
func (m *IPMask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPMask.Marshal(b, m, deterministic)
}
func (m *IPMask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPMask.Merge(m, src)
}
func (m *IPMask) XXX_Size() int {
	return xxx_messageInfo_IPMask.Size(m)
}
func (m *IPMask) XXX_DiscardUnknown() {
	xxx_messageInfo_IPMask.DiscardUnknown(m)
}

var xxx_messageInfo_IPMask proto.InternalMessageInfo

func (m *IPMask) GetType() IPType {
	if m != nil {
		return m.Type
	}
	return IPType_IPV4
}

func (m *IPMask) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

type IPAddress struct {
	// Specify the type of this address.
	Type IPType `protobuf:"varint,1,opt,name=type,proto3,enum=v1alpha1.IPType" json:"type,omitempty"`
	// The array of bytes that make up the ip address.
	Address              [][]byte `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPAddress) Reset()         { *m = IPAddress{} }
func (m *IPAddress) String() string { return proto.CompactTextString(m) }
func (*IPAddress) ProtoMessage()    {}
func (*IPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{25}
}

func (m *IPAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAddress.Unmarshal(m, b)
}
func (m *IPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAddress.Marshal(b, m, deterministic)
}
func (m *IPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAddress.Merge(m, src)
}
func (m *IPAddress) XXX_Size() int {
	return xxx_messageInfo_IPAddress.Size(m)
}
func (m *IPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_IPAddress proto.InternalMessageInfo

func (m *IPAddress) GetType() IPType {
	if m != nil {
		return m.Type
	}
	return IPType_IPV4
}

func (m *IPAddress) GetAddress() [][]byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type MACAddress struct {
	// The bytes that make up the hardware address. Should be 6 bytes.
	Address              [][]byte `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MACAddress) Reset()         { *m = MACAddress{} }
func (m *MACAddress) String() string { return proto.CompactTextString(m) }
func (*MACAddress) ProtoMessage()    {}
func (*MACAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{26}
}

func (m *MACAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MACAddress.Unmarshal(m, b)
}
func (m *MACAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MACAddress.Marshal(b, m, deterministic)
}
func (m *MACAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MACAddress.Merge(m, src)
}
func (m *MACAddress) XXX_Size() int {
	return xxx_messageInfo_MACAddress.Size(m)
}
func (m *MACAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MACAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MACAddress proto.InternalMessageInfo

func (m *MACAddress) GetAddress() [][]byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type LinkAddress struct {
	// Specify the type of this address object, ipv4 or ipv6.
	Type IPType `protobuf:"varint,1,opt,name=type,proto3,enum=v1alpha1.IPType" json:"type,omitempty"`
	// How is this address assigned.
	Assignment LinkAddressAssignment `protobuf:"varint,2,opt,name=assignment,proto3,enum=v1alpha1.LinkAddressAssignment" json:"assignment,omitempty"`
	// The actual address of this object. Should be formatted
	// so that the "net" package can parse the string into an address.
	Address *IPCIDR `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Gateway address of this address. Should be formatted
	// so that the "net" package can parse the string into an address.
	Gateway *IPAddress `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// DNS server address of this link. Should be formatted
	// so that the "net" package can parse the string into an address.
	DnsServer            *IPAddress `protobuf:"bytes,7,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LinkAddress) Reset()         { *m = LinkAddress{} }
func (m *LinkAddress) String() string { return proto.CompactTextString(m) }
func (*LinkAddress) ProtoMessage()    {}
func (*LinkAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{27}
}

func (m *LinkAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkAddress.Unmarshal(m, b)
}
func (m *LinkAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkAddress.Marshal(b, m, deterministic)
}
func (m *LinkAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkAddress.Merge(m, src)
}
func (m *LinkAddress) XXX_Size() int {
	return xxx_messageInfo_LinkAddress.Size(m)
}
func (m *LinkAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkAddress.DiscardUnknown(m)
}

var xxx_messageInfo_LinkAddress proto.InternalMessageInfo

func (m *LinkAddress) GetType() IPType {
	if m != nil {
		return m.Type
	}
	return IPType_IPV4
}

func (m *LinkAddress) GetAssignment() LinkAddressAssignment {
	if m != nil {
		return m.Assignment
	}
	return LinkAddressAssignment_STATIC
}

func (m *LinkAddress) GetAddress() *IPCIDR {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LinkAddress) GetGateway() *IPAddress {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *LinkAddress) GetDnsServer() *IPAddress {
	if m != nil {
		return m.DnsServer
	}
	return nil
}

type LinkMACAddress struct {
	// Assignment type for the MAC address with this.
	Assignment LinkMACAddressAssignment `protobuf:"varint,1,opt,name=assignment,proto3,enum=v1alpha1.LinkMACAddressAssignment" json:"assignment,omitempty"`
	// Should be a string formatted as xx:xx:xx:xx:xx:xx, so that
	// "net" can parse it correctly, otherwise will throw an error.
	Address *MACAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Broadcast mac address.
	BroadcastAddress     *MACAddress `protobuf:"bytes,3,opt,name=broadcast_address,json=broadcastAddress,proto3" json:"broadcast_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LinkMACAddress) Reset()         { *m = LinkMACAddress{} }
func (m *LinkMACAddress) String() string { return proto.CompactTextString(m) }
func (*LinkMACAddress) ProtoMessage()    {}
func (*LinkMACAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{28}
}

func (m *LinkMACAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkMACAddress.Unmarshal(m, b)
}
func (m *LinkMACAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkMACAddress.Marshal(b, m, deterministic)
}
func (m *LinkMACAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkMACAddress.Merge(m, src)
}
func (m *LinkMACAddress) XXX_Size() int {
	return xxx_messageInfo_LinkMACAddress.Size(m)
}
func (m *LinkMACAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkMACAddress.DiscardUnknown(m)
}

var xxx_messageInfo_LinkMACAddress proto.InternalMessageInfo

func (m *LinkMACAddress) GetAssignment() LinkMACAddressAssignment {
	if m != nil {
		return m.Assignment
	}
	return LinkMACAddressAssignment_HW
}

func (m *LinkMACAddress) GetAddress() *MACAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LinkMACAddress) GetBroadcastAddress() *MACAddress {
	if m != nil {
		return m.BroadcastAddress
	}
	return nil
}

type Neighbor struct {
	// Whether this neighbor is IPV4 or 6.
	NeighborAddrType IPType `protobuf:"varint,1,opt,name=neighbor_addr_type,json=neighborAddrType,proto3,enum=v1alpha1.IPType" json:"neighbor_addr_type,omitempty"`
	// The address of this neighbor (ip)
	IpAddress *IPAddress `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Link-layer address of this neighbor.
	MacAddress *MACAddress `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// The state of this neighbor.
	State                NeighborState `protobuf:"varint,4,opt,name=state,proto3,enum=v1alpha1.NeighborState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Neighbor) Reset()         { *m = Neighbor{} }
func (m *Neighbor) String() string { return proto.CompactTextString(m) }
func (*Neighbor) ProtoMessage()    {}
func (*Neighbor) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{29}
}

func (m *Neighbor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Neighbor.Unmarshal(m, b)
}
func (m *Neighbor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Neighbor.Marshal(b, m, deterministic)
}
func (m *Neighbor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neighbor.Merge(m, src)
}
func (m *Neighbor) XXX_Size() int {
	return xxx_messageInfo_Neighbor.Size(m)
}
func (m *Neighbor) XXX_DiscardUnknown() {
	xxx_messageInfo_Neighbor.DiscardUnknown(m)
}

var xxx_messageInfo_Neighbor proto.InternalMessageInfo

func (m *Neighbor) GetNeighborAddrType() IPType {
	if m != nil {
		return m.NeighborAddrType
	}
	return IPType_IPV4
}

func (m *Neighbor) GetIpAddress() *IPAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *Neighbor) GetMacAddress() *MACAddress {
	if m != nil {
		return m.MacAddress
	}
	return nil
}

func (m *Neighbor) GetState() NeighborState {
	if m != nil {
		return m.State
	}
	return NeighborState_PERMANENT
}

type GetNeighborRequest struct {
	// Specify the elements that you want to sort by.
	FilterElems map[string]string `protobuf:"bytes,1,rep,name=filter_elems,json=filterElems,proto3" json:"filter_elems,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Specify the maximum number of neighbors that you want back.
	MaxNeighbors         int32    `protobuf:"varint,2,opt,name=max_neighbors,json=maxNeighbors,proto3" json:"max_neighbors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNeighborRequest) Reset()         { *m = GetNeighborRequest{} }
func (m *GetNeighborRequest) String() string { return proto.CompactTextString(m) }
func (*GetNeighborRequest) ProtoMessage()    {}
func (*GetNeighborRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{30}
}

func (m *GetNeighborRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNeighborRequest.Unmarshal(m, b)
}
func (m *GetNeighborRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNeighborRequest.Marshal(b, m, deterministic)
}
func (m *GetNeighborRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNeighborRequest.Merge(m, src)
}
func (m *GetNeighborRequest) XXX_Size() int {
	return xxx_messageInfo_GetNeighborRequest.Size(m)
}
func (m *GetNeighborRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNeighborRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNeighborRequest proto.InternalMessageInfo

func (m *GetNeighborRequest) GetFilterElems() map[string]string {
	if m != nil {
		return m.FilterElems
	}
	return nil
}

func (m *GetNeighborRequest) GetMaxNeighbors() int32 {
	if m != nil {
		return m.MaxNeighbors
	}
	return 0
}

type GetNeighborResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating getting neighbor.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The neighbor that is returned.
	Neighbor             *Neighbor `protobuf:"bytes,3,opt,name=neighbor,proto3" json:"neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNeighborResponse) Reset()         { *m = GetNeighborResponse{} }
func (m *GetNeighborResponse) String() string { return proto.CompactTextString(m) }
func (*GetNeighborResponse) ProtoMessage()    {}
func (*GetNeighborResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{31}
}

func (m *GetNeighborResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNeighborResponse.Unmarshal(m, b)
}
func (m *GetNeighborResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNeighborResponse.Marshal(b, m, deterministic)
}
func (m *GetNeighborResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNeighborResponse.Merge(m, src)
}
func (m *GetNeighborResponse) XXX_Size() int {
	return xxx_messageInfo_GetNeighborResponse.Size(m)
}
func (m *GetNeighborResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNeighborResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNeighborResponse proto.InternalMessageInfo

func (m *GetNeighborResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetNeighborResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetNeighborResponse) GetNeighbor() *Neighbor {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

type GetAllNeighborsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllNeighborsRequest) Reset()         { *m = GetAllNeighborsRequest{} }
func (m *GetAllNeighborsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllNeighborsRequest) ProtoMessage()    {}
func (*GetAllNeighborsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{32}
}

func (m *GetAllNeighborsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllNeighborsRequest.Unmarshal(m, b)
}
func (m *GetAllNeighborsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllNeighborsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllNeighborsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllNeighborsRequest.Merge(m, src)
}
func (m *GetAllNeighborsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllNeighborsRequest.Size(m)
}
func (m *GetAllNeighborsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllNeighborsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllNeighborsRequest proto.InternalMessageInfo

type GetAllNeighborsResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this neighbor schema.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The neighbors that are returned.
	Neighbors            []*Neighbor `protobuf:"bytes,3,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllNeighborsResponse) Reset()         { *m = GetAllNeighborsResponse{} }
func (m *GetAllNeighborsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllNeighborsResponse) ProtoMessage()    {}
func (*GetAllNeighborsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{33}
}

func (m *GetAllNeighborsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllNeighborsResponse.Unmarshal(m, b)
}
func (m *GetAllNeighborsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllNeighborsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllNeighborsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllNeighborsResponse.Merge(m, src)
}
func (m *GetAllNeighborsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllNeighborsResponse.Size(m)
}
func (m *GetAllNeighborsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllNeighborsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllNeighborsResponse proto.InternalMessageInfo

func (m *GetAllNeighborsResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *GetAllNeighborsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetAllNeighborsResponse) GetNeighbors() []*Neighbor {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type CreateNeighborRequest struct {
	Neighbor             []*Neighbor `protobuf:"bytes,1,rep,name=neighbor,proto3" json:"neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateNeighborRequest) Reset()         { *m = CreateNeighborRequest{} }
func (m *CreateNeighborRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNeighborRequest) ProtoMessage()    {}
func (*CreateNeighborRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{34}
}

func (m *CreateNeighborRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNeighborRequest.Unmarshal(m, b)
}
func (m *CreateNeighborRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNeighborRequest.Marshal(b, m, deterministic)
}
func (m *CreateNeighborRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNeighborRequest.Merge(m, src)
}
func (m *CreateNeighborRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNeighborRequest.Size(m)
}
func (m *CreateNeighborRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNeighborRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNeighborRequest proto.InternalMessageInfo

func (m *CreateNeighborRequest) GetNeighbor() []*Neighbor {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

type CreateNeighborResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this neighbor schema.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNeighborResponse) Reset()         { *m = CreateNeighborResponse{} }
func (m *CreateNeighborResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNeighborResponse) ProtoMessage()    {}
func (*CreateNeighborResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{35}
}

func (m *CreateNeighborResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNeighborResponse.Unmarshal(m, b)
}
func (m *CreateNeighborResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNeighborResponse.Marshal(b, m, deterministic)
}
func (m *CreateNeighborResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNeighborResponse.Merge(m, src)
}
func (m *CreateNeighborResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNeighborResponse.Size(m)
}
func (m *CreateNeighborResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNeighborResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNeighborResponse proto.InternalMessageInfo

func (m *CreateNeighborResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *CreateNeighborResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteNeighborRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNeighborRequest) Reset()         { *m = DeleteNeighborRequest{} }
func (m *DeleteNeighborRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNeighborRequest) ProtoMessage()    {}
func (*DeleteNeighborRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{36}
}

func (m *DeleteNeighborRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNeighborRequest.Unmarshal(m, b)
}
func (m *DeleteNeighborRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNeighborRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNeighborRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNeighborRequest.Merge(m, src)
}
func (m *DeleteNeighborRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNeighborRequest.Size(m)
}
func (m *DeleteNeighborRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNeighborRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNeighborRequest proto.InternalMessageInfo

type DeleteNeighborResponse struct {
	// Response code for this RPC call.
	StatusCode ReturnStatusCodes `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=v1alpha1.ReturnStatusCodes" json:"status_code,omitempty"`
	// Error if there is any with updating this neighbor schema.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The returned deleted neighbor object.
	Neighbor             *Neighbor `protobuf:"bytes,3,opt,name=neighbor,proto3" json:"neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteNeighborResponse) Reset()         { *m = DeleteNeighborResponse{} }
func (m *DeleteNeighborResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNeighborResponse) ProtoMessage()    {}
func (*DeleteNeighborResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{37}
}

func (m *DeleteNeighborResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNeighborResponse.Unmarshal(m, b)
}
func (m *DeleteNeighborResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNeighborResponse.Marshal(b, m, deterministic)
}
func (m *DeleteNeighborResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNeighborResponse.Merge(m, src)
}
func (m *DeleteNeighborResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNeighborResponse.Size(m)
}
func (m *DeleteNeighborResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNeighborResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNeighborResponse proto.InternalMessageInfo

func (m *DeleteNeighborResponse) GetStatusCode() ReturnStatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return ReturnStatusCodes_OK
}

func (m *DeleteNeighborResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteNeighborResponse) GetNeighbor() *Neighbor {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

type UpdateNeighborRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNeighborRequest) Reset()         { *m = UpdateNeighborRequest{} }
func (m *UpdateNeighborRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNeighborRequest) ProtoMessage()    {}
func (*UpdateNeighborRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{38}
}

func (m *UpdateNeighborRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNeighborRequest.Unmarshal(m, b)
}
func (m *UpdateNeighborRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNeighborRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNeighborRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNeighborRequest.Merge(m, src)
}
func (m *UpdateNeighborRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNeighborRequest.Size(m)
}
func (m *UpdateNeighborRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNeighborRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNeighborRequest proto.InternalMessageInfo

type UpdateNeighborResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNeighborResponse) Reset()         { *m = UpdateNeighborResponse{} }
func (m *UpdateNeighborResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNeighborResponse) ProtoMessage()    {}
func (*UpdateNeighborResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d763a251f529009a, []int{39}
}

func (m *UpdateNeighborResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNeighborResponse.Unmarshal(m, b)
}
func (m *UpdateNeighborResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNeighborResponse.Marshal(b, m, deterministic)
}
func (m *UpdateNeighborResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNeighborResponse.Merge(m, src)
}
func (m *UpdateNeighborResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNeighborResponse.Size(m)
}
func (m *UpdateNeighborResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNeighborResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNeighborResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("v1alpha1.ReturnStatusCodes", ReturnStatusCodes_name, ReturnStatusCodes_value)
	proto.RegisterEnum("v1alpha1.LinkTypes", LinkTypes_name, LinkTypes_value)
	proto.RegisterEnum("v1alpha1.LinkElements", LinkElements_name, LinkElements_value)
	proto.RegisterEnum("v1alpha1.RouteElements", RouteElements_name, RouteElements_value)
	proto.RegisterEnum("v1alpha1.IPType", IPType_name, IPType_value)
	proto.RegisterEnum("v1alpha1.LinkAddressAssignment", LinkAddressAssignment_name, LinkAddressAssignment_value)
	proto.RegisterEnum("v1alpha1.LinkMACAddressAssignment", LinkMACAddressAssignment_name, LinkMACAddressAssignment_value)
	proto.RegisterEnum("v1alpha1.NeighborElements", NeighborElements_name, NeighborElements_value)
	proto.RegisterEnum("v1alpha1.NeighborState", NeighborState_name, NeighborState_value)
	proto.RegisterType((*CreateLinkRequest)(nil), "v1alpha1.CreateLinkRequest")
	proto.RegisterType((*CreateLinkResponse)(nil), "v1alpha1.CreateLinkResponse")
	proto.RegisterType((*UpdateLinkRequest)(nil), "v1alpha1.UpdateLinkRequest")
	proto.RegisterType((*UpdateLinkResponse)(nil), "v1alpha1.UpdateLinkResponse")
	proto.RegisterType((*DeleteLinkRequest)(nil), "v1alpha1.DeleteLinkRequest")
	proto.RegisterType((*DeleteLinkResponse)(nil), "v1alpha1.DeleteLinkResponse")
	proto.RegisterType((*GetLinkRequest)(nil), "v1alpha1.GetLinkRequest")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.GetLinkRequest.FilterElemsEntry")
	proto.RegisterType((*GetLinkResponse)(nil), "v1alpha1.GetLinkResponse")
	proto.RegisterType((*GetAllLinksRequest)(nil), "v1alpha1.GetAllLinksRequest")
	proto.RegisterType((*GetAllLinksResponse)(nil), "v1alpha1.GetAllLinksResponse")
	proto.RegisterType((*Link)(nil), "v1alpha1.Link")
	proto.RegisterType((*LinkAttributes)(nil), "v1alpha1.LinkAttributes")
	proto.RegisterType((*GetRouteRequest)(nil), "v1alpha1.GetRouteRequest")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.GetRouteRequest.FilterElemsEntry")
	proto.RegisterType((*GetRouteResponse)(nil), "v1alpha1.GetRouteResponse")
	proto.RegisterType((*GetAllRoutesRequest)(nil), "v1alpha1.GetAllRoutesRequest")
	proto.RegisterType((*GetAllRoutesResponse)(nil), "v1alpha1.GetAllRoutesResponse")
	proto.RegisterType((*CreateStaticRouteRequest)(nil), "v1alpha1.CreateStaticRouteRequest")
	proto.RegisterType((*CreateStaticRouteResponse)(nil), "v1alpha1.CreateStaticRouteResponse")
	proto.RegisterType((*DeleteStaticRouteRequest)(nil), "v1alpha1.DeleteStaticRouteRequest")
	proto.RegisterType((*DeleteStaticRouteResponse)(nil), "v1alpha1.DeleteStaticRouteResponse")
	proto.RegisterType((*UpdateStaticRouteRequest)(nil), "v1alpha1.UpdateStaticRouteRequest")
	proto.RegisterType((*UpdateStaticRouteResponse)(nil), "v1alpha1.UpdateStaticRouteResponse")
	proto.RegisterType((*Route)(nil), "v1alpha1.Route")
	proto.RegisterType((*IPCIDR)(nil), "v1alpha1.IPCIDR")
	proto.RegisterType((*IPMask)(nil), "v1alpha1.IPMask")
	proto.RegisterType((*IPAddress)(nil), "v1alpha1.IPAddress")
	proto.RegisterType((*MACAddress)(nil), "v1alpha1.MACAddress")
	proto.RegisterType((*LinkAddress)(nil), "v1alpha1.LinkAddress")
	proto.RegisterType((*LinkMACAddress)(nil), "v1alpha1.LinkMACAddress")
	proto.RegisterType((*Neighbor)(nil), "v1alpha1.Neighbor")
	proto.RegisterType((*GetNeighborRequest)(nil), "v1alpha1.GetNeighborRequest")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.GetNeighborRequest.FilterElemsEntry")
	proto.RegisterType((*GetNeighborResponse)(nil), "v1alpha1.GetNeighborResponse")
	proto.RegisterType((*GetAllNeighborsRequest)(nil), "v1alpha1.GetAllNeighborsRequest")
	proto.RegisterType((*GetAllNeighborsResponse)(nil), "v1alpha1.GetAllNeighborsResponse")
	proto.RegisterType((*CreateNeighborRequest)(nil), "v1alpha1.CreateNeighborRequest")
	proto.RegisterType((*CreateNeighborResponse)(nil), "v1alpha1.CreateNeighborResponse")
	proto.RegisterType((*DeleteNeighborRequest)(nil), "v1alpha1.DeleteNeighborRequest")
	proto.RegisterType((*DeleteNeighborResponse)(nil), "v1alpha1.DeleteNeighborResponse")
	proto.RegisterType((*UpdateNeighborRequest)(nil), "v1alpha1.UpdateNeighborRequest")
	proto.RegisterType((*UpdateNeighborResponse)(nil), "v1alpha1.UpdateNeighborResponse")
}

func init() { proto.RegisterFile("node_control.proto", fileDescriptor_d763a251f529009a) }

var fileDescriptor_d763a251f529009a = []byte{
	// 2249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0xcf, 0x8f, 0x1b, 0x49,
	0xf5, 0x9f, 0xb6, 0xc7, 0xbf, 0x9e, 0xc7, 0x4e, 0x4d, 0xcd, 0x2f, 0x8f, 0x33, 0xd9, 0xcc, 0xf6,
	0xee, 0xf7, 0x9b, 0x60, 0x69, 0x07, 0x76, 0xb2, 0x64, 0x57, 0x08, 0x16, 0x7a, 0xec, 0x9a, 0x99,
	0x56, 0xec, 0xb6, 0x29, 0x77, 0x26, 0x09, 0x12, 0x58, 0x1d, 0xbb, 0x26, 0xb1, 0x62, 0xb7, 0x4d,
	0x77, 0x3b, 0x9b, 0x39, 0x21, 0xc1, 0x81, 0x03, 0x42, 0x1c, 0x90, 0x90, 0x90, 0x90, 0xe0, 0xc2,
	0x81, 0xbf, 0x81, 0x03, 0x47, 0x0e, 0xf0, 0x27, 0x70, 0xe4, 0xc4, 0x5f, 0x81, 0xaa, 0xaa, 0xbb,
	0xdd, 0x6d, 0xb7, 0x27, 0x11, 0xcb, 0x00, 0xb7, 0xfa, 0xf1, 0xa9, 0x4f, 0xbd, 0xf7, 0xea, 0x55,
	0xbd, 0xd7, 0xaf, 0x01, 0xdb, 0x93, 0x01, 0xeb, 0xf5, 0x27, 0xb6, 0xe7, 0x4c, 0x46, 0x47, 0x53,
	0x67, 0xe2, 0x4d, 0x70, 0xfe, 0xf5, 0xc7, 0xd6, 0x68, 0xfa, 0xd2, 0xfa, 0x58, 0xfd, 0x14, 0x36,
	0xeb, 0x0e, 0xb3, 0x3c, 0xd6, 0x1c, 0xda, 0xaf, 0x28, 0xfb, 0xe1, 0x8c, 0xb9, 0x1e, 0x56, 0x61,
	0x7d, 0x34, 0xb4, 0x5f, 0x55, 0x94, 0xc3, 0xf4, 0xfd, 0xe2, 0x71, 0xf9, 0x28, 0x40, 0x1f, 0x09,
	0x90, 0x98, 0x53, 0xff, 0xa6, 0x00, 0x8e, 0xae, 0x74, 0xa7, 0x13, 0xdb, 0x65, 0xf8, 0x9b, 0x50,
	0x74, 0x3d, 0xcb, 0x9b, 0xb9, 0xbd, 0xfe, 0x64, 0xc0, 0x2a, 0xca, 0xa1, 0x72, 0xbf, 0x7c, 0x7c,
	0x7b, 0xce, 0x40, 0x99, 0x37, 0x73, 0xec, 0xae, 0x80, 0xd4, 0x27, 0x03, 0xe6, 0x52, 0x70, 0xc3,
	0x0e, 0xde, 0x86, 0x0c, 0x73, 0x9c, 0x89, 0x53, 0x49, 0x1d, 0x2a, 0xf7, 0x0b, 0x54, 0x76, 0xf0,
	0x03, 0x28, 0xb9, 0xb3, 0x7e, 0x9f, 0xb9, 0x6e, 0x8f, 0x6f, 0xed, 0x56, 0xd2, 0x89, 0x72, 0x6d,
	0xf8, 0x20, 0xde, 0x71, 0xf1, 0xb7, 0x00, 0xcf, 0x6c, 0x7f, 0xe4, 0x72, 0x36, 0xf2, 0x57, 0xae,
	0x27, 0xae, 0xdc, 0x8c, 0x22, 0xc5, 0x72, 0xf5, 0x11, 0x6c, 0x3e, 0x9e, 0x0e, 0x16, 0xec, 0x82,
	0x61, 0xdd, 0xb6, 0xc6, 0x52, 0xab, 0x02, 0x15, 0xed, 0xd0, 0x56, 0x5c, 0xe2, 0x55, 0xb6, 0x7a,
	0x09, 0x38, 0x4a, 0x76, 0x73, 0xa6, 0x52, 0xef, 0xc1, 0x66, 0x83, 0x8d, 0xd8, 0x2a, 0xb1, 0xd3,
	0x81, 0xd8, 0xea, 0x4f, 0x15, 0xc0, 0x51, 0xe4, 0xbf, 0x45, 0xa6, 0x07, 0x50, 0x1a, 0x08, 0xce,
	0x81, 0x6f, 0xee, 0x54, 0xf2, 0x41, 0xf9, 0x20, 0x69, 0xe9, 0x3f, 0x2a, 0x50, 0x3e, 0x63, 0x5e,
	0x54, 0xe0, 0x26, 0x6c, 0x5c, 0x0e, 0x47, 0x1e, 0x73, 0x7a, 0x6c, 0xc4, 0xc6, 0xae, 0xef, 0x87,
	0x5f, 0x99, 0xd3, 0xc4, 0xf1, 0x47, 0xa7, 0x02, 0x4c, 0x38, 0x96, 0xd8, 0x9e, 0x73, 0x45, 0x8b,
	0x97, 0xf3, 0x11, 0x7c, 0x1b, 0x0a, 0x63, 0xeb, 0x4d, 0x28, 0x91, 0x72, 0x3f, 0x43, 0xf3, 0x63,
	0xeb, 0x8d, 0xd8, 0xbd, 0xfa, 0x39, 0xa0, 0xc5, 0xd5, 0x18, 0x41, 0xfa, 0x15, 0xbb, 0xf2, 0x4f,
	0x99, 0x37, 0xb9, 0xb1, 0x5f, 0x5b, 0xa3, 0x19, 0x0b, 0x8c, 0x2d, 0x3a, 0xdf, 0x48, 0x7d, 0xa6,
	0xa8, 0x3f, 0x53, 0xe0, 0x56, 0x28, 0xcd, 0x0d, 0xde, 0x81, 0x0f, 0x21, 0x73, 0x9d, 0xef, 0xcb,
	0x49, 0x75, 0x1b, 0xf0, 0x19, 0xf3, 0xb4, 0x91, 0x74, 0x62, 0xdf, 0x3c, 0xea, 0x2f, 0x14, 0xd8,
	0x8a, 0x0d, 0xff, 0xd7, 0xe5, 0xfc, 0x71, 0x0a, 0xd6, 0x79, 0x3f, 0xf1, 0x46, 0x7d, 0x15, 0x72,
	0xd6, 0x60, 0xe0, 0x30, 0x37, 0xf0, 0x9f, 0x9d, 0x38, 0x89, 0x26, 0x27, 0x69, 0x80, 0xc2, 0x35,
	0x48, 0x8f, 0xad, 0x7e, 0x25, 0x2d, 0x6e, 0x60, 0x25, 0x0e, 0x6e, 0x69, 0xf5, 0x00, 0xcf, 0x41,
	0xf8, 0x1e, 0xac, 0x7b, 0x57, 0x53, 0x56, 0x59, 0x17, 0xca, 0x6e, 0xc5, 0xc1, 0xe6, 0xd5, 0x94,
	0xb9, 0x54, 0x00, 0xb8, 0x13, 0x8c, 0xbd, 0x59, 0x25, 0x73, 0xa8, 0xdc, 0x2f, 0x51, 0xde, 0xe4,
	0x0a, 0x0f, 0xed, 0x01, 0x7b, 0x53, 0xc9, 0x8a, 0x31, 0xd9, 0xc1, 0x9f, 0x01, 0x58, 0x9e, 0xe7,
	0x0c, 0x9f, 0xcf, 0x3c, 0xe6, 0x56, 0x72, 0x49, 0x32, 0x68, 0xe1, 0x3c, 0x8d, 0x60, 0xd5, 0x2b,
	0x28, 0xc7, 0x67, 0x71, 0x19, 0x52, 0xb3, 0xa9, 0xb0, 0x45, 0x9e, 0xa6, 0x66, 0x53, 0x7c, 0x17,
	0x8a, 0x96, 0x33, 0xed, 0x31, 0xdb, 0x7a, 0x3e, 0x62, 0x03, 0x61, 0xe8, 0x3c, 0x05, 0xcb, 0x99,
	0x12, 0x39, 0x82, 0x2b, 0x90, 0x1b, 0x5c, 0xd9, 0xd6, 0x78, 0x28, 0xb5, 0xcf, 0xd3, 0xa0, 0x8b,
	0x0f, 0xa0, 0x30, 0x9e, 0x8d, 0xbc, 0x61, 0xdf, 0x72, 0x3d, 0xa1, 0x6c, 0x9e, 0xce, 0x07, 0xd4,
	0x3f, 0x49, 0xaf, 0xa5, 0x93, 0x99, 0xc7, 0x82, 0x4b, 0xd7, 0x4a, 0xbc, 0x74, 0xb5, 0xd8, 0xa5,
	0x8b, 0x2e, 0x78, 0xcb, 0xad, 0xbb, 0x03, 0xc0, 0x6f, 0x9d, 0x33, 0x11, 0x76, 0x91, 0xd7, 0x8e,
	0xdf, 0x43, 0x41, 0xf1, 0xe5, 0xef, 0xdd, 0xcf, 0x15, 0x40, 0x73, 0x81, 0x6e, 0xd0, 0xa1, 0xff,
	0x0f, 0x32, 0x42, 0x07, 0xdf, 0xbd, 0x6e, 0x45, 0xd8, 0xc4, 0xde, 0x72, 0x56, 0xdd, 0x09, 0xae,
	0x98, 0xd4, 0x2f, 0xb8, 0x7a, 0xbf, 0x54, 0x60, 0x3b, 0x3e, 0x7e, 0x83, 0xa2, 0xde, 0x83, 0xac,
	0x6f, 0xee, 0x15, 0xb2, 0xfa, 0xd3, 0xaa, 0x06, 0x15, 0x19, 0xba, 0x39, 0xff, 0xb0, 0x1f, 0x73,
	0x83, 0x50, 0x5f, 0x79, 0xfe, 0xab, 0xf4, 0xfd, 0xbd, 0x02, 0xfb, 0x09, 0x1c, 0x37, 0xa8, 0xdd,
	0x27, 0x50, 0xba, 0xb4, 0x86, 0x23, 0x36, 0xe8, 0x85, 0x4a, 0x26, 0x0a, 0xb8, 0x21, 0x51, 0x34,
	0x54, 0x55, 0x86, 0xb9, 0x7f, 0x5d, 0xd5, 0x5f, 0x29, 0xb0, 0x9f, 0xc0, 0xf1, 0x9f, 0xf1, 0xb9,
	0xeb, 0x04, 0xd3, 0xa0, 0x22, 0xd3, 0x8a, 0xeb, 0x74, 0x4b, 0x5d, 0xeb, 0xb6, 0x13, 0xd8, 0x4f,
	0xa0, 0xb8, 0xc1, 0x04, 0xe5, 0x77, 0x0a, 0x64, 0xc4, 0x2e, 0xf8, 0x18, 0x8a, 0x03, 0xe6, 0x7a,
	0x43, 0xdb, 0xf2, 0x86, 0x13, 0x5b, 0xb0, 0x17, 0x8f, 0xd1, 0x9c, 0x5d, 0xef, 0xd4, 0xf5, 0x06,
	0xa5, 0x51, 0x10, 0xfe, 0x08, 0x72, 0x2f, 0x2c, 0x8f, 0x7d, 0x61, 0x5d, 0xf9, 0x7a, 0x6d, 0x45,
	0xf1, 0x61, 0x60, 0xf0, 0x31, 0x78, 0x17, 0xb2, 0x63, 0xe6, 0x39, 0xc3, 0xbe, 0x78, 0x01, 0x33,
	0xd4, 0xef, 0xf1, 0xc7, 0x71, 0x68, 0x7b, 0xcc, 0xb9, 0xb4, 0xfa, 0x4c, 0xbc, 0xf0, 0x05, 0x3a,
	0x1f, 0x50, 0xbf, 0x0f, 0x59, 0xb9, 0x37, 0xdf, 0x2e, 0x88, 0x44, 0xca, 0x35, 0xdb, 0x05, 0x71,
	0xe8, 0x43, 0x58, 0x1f, 0x5b, 0x6e, 0x90, 0x0a, 0xc6, 0x54, 0x69, 0x59, 0xee, 0x2b, 0x2a, 0x66,
	0xd5, 0x13, 0x4e, 0xcf, 0xfb, 0x1c, 0x2f, 0x62, 0x91, 0x34, 0x6c, 0x0c, 0xcf, 0x23, 0x91, 0x1f,
	0x88, 0x70, 0x84, 0xb5, 0xe4, 0x73, 0x3c, 0x82, 0x42, 0xb8, 0xff, 0x3b, 0xd2, 0x54, 0xe2, 0x51,
	0x75, 0x23, 0x14, 0x5b, 0xfd, 0x7f, 0x80, 0x79, 0x94, 0x8c, 0xe2, 0x94, 0x38, 0xee, 0x27, 0x29,
	0x28, 0x46, 0xe2, 0xef, 0x3b, 0xee, 0xfb, 0x6d, 0x00, 0xcb, 0x75, 0x87, 0x2f, 0xec, 0x31, 0xb3,
	0x3d, 0xa1, 0x44, 0xf9, 0xf8, 0x6e, 0x62, 0x40, 0xd7, 0x42, 0x18, 0x8d, 0x2c, 0xc1, 0xb5, 0xb9,
	0x40, 0xe9, 0x15, 0x3e, 0x12, 0x9e, 0x40, 0xc4, 0x3f, 0xb2, 0xef, 0xe0, 0x1f, 0xc7, 0x00, 0x03,
	0xdb, 0xed, 0xb9, 0xcc, 0x79, 0xcd, 0x1c, 0x3f, 0x76, 0x27, 0xae, 0x28, 0x0c, 0x6c, 0xb7, 0x2b,
	0x50, 0xea, 0x9f, 0x15, 0x19, 0xb6, 0x23, 0x26, 0x3b, 0x89, 0xa9, 0x28, 0xcd, 0xa1, 0xae, 0x4a,
	0x43, 0x56, 0x68, 0x79, 0x14, 0x3d, 0x1e, 0x2e, 0xc7, 0xf6, 0x9c, 0x20, 0x92, 0xc3, 0x84, 0x9a,
	0x6a, 0xb0, 0xf9, 0xdc, 0x99, 0x58, 0x03, 0x1e, 0xce, 0x7b, 0x71, 0xfb, 0x24, 0xaf, 0x44, 0x21,
	0xdc, 0x1f, 0x51, 0xff, 0xae, 0x40, 0xde, 0x60, 0xc3, 0x17, 0x2f, 0x9f, 0x4f, 0x1c, 0xfc, 0x39,
	0x60, 0xdb, 0x6f, 0x0b, 0xba, 0xde, 0xb5, 0x47, 0x8b, 0x02, 0x2c, 0xe7, 0xe2, 0x23, 0xdc, 0x94,
	0xc3, 0x69, 0x2f, 0xae, 0x42, 0xb2, 0x29, 0x87, 0xd3, 0xc0, 0x6e, 0x5f, 0x87, 0xe2, 0xd8, 0xea,
	0xbf, 0x93, 0xf4, 0x30, 0xb6, 0xfa, 0x5a, 0x78, 0xc8, 0x19, 0xfe, 0xcc, 0x04, 0x39, 0xdc, 0xde,
	0x7c, 0x41, 0xa0, 0x0d, 0x7f, 0x92, 0x18, 0x95, 0x28, 0xf5, 0x2f, 0x8a, 0x48, 0x8a, 0x83, 0xb9,
	0xe0, 0x81, 0xec, 0x24, 0xa6, 0x3b, 0x1f, 0xc5, 0xd2, 0x9d, 0x85, 0x35, 0x6f, 0xc9, 0x78, 0x3e,
	0x80, 0x12, 0xcf, 0x78, 0x02, 0xd3, 0x04, 0x49, 0xcf, 0xc6, 0xd8, 0x7a, 0x13, 0x10, 0x7d, 0xf9,
	0xbc, 0xe7, 0xd7, 0x32, 0x97, 0x9f, 0x4b, 0x76, 0x83, 0x61, 0xe8, 0x08, 0xf2, 0x81, 0x32, 0xfe,
	0xe1, 0xe0, 0x65, 0x5b, 0xd3, 0x10, 0xa3, 0x56, 0x60, 0x57, 0xe6, 0x3a, 0xa1, 0xba, 0x41, 0x1a,
	0xf4, 0x5b, 0x05, 0xf6, 0x96, 0xa6, 0x6e, 0x50, 0xf2, 0xaf, 0x41, 0x61, 0x7e, 0x0c, 0x32, 0x88,
	0x26, 0x89, 0x3e, 0x07, 0xa9, 0x67, 0xb0, 0x23, 0xd3, 0x99, 0x45, 0x3f, 0x89, 0x1a, 0x41, 0x59,
	0xc9, 0x34, 0x37, 0xc2, 0x08, 0x76, 0x17, 0x89, 0x6e, 0x30, 0x9c, 0xee, 0xc1, 0x8e, 0x4c, 0x4d,
	0x16, 0xc4, 0x56, 0x7f, 0xa3, 0xc0, 0xee, 0xe2, 0xcc, 0xff, 0x90, 0xab, 0xec, 0xc1, 0x8e, 0xcc,
	0x3b, 0x16, 0xe5, 0xae, 0xc0, 0xee, 0xe2, 0x84, 0x14, 0xbb, 0xf6, 0x57, 0x05, 0x36, 0x97, 0x44,
	0xc3, 0x59, 0x48, 0xb5, 0x1f, 0xa1, 0x35, 0xbc, 0x01, 0x79, 0xad, 0x5e, 0x27, 0x1d, 0x93, 0x34,
	0x90, 0x82, 0x77, 0x60, 0xb3, 0x43, 0x68, 0x4b, 0xef, 0x76, 0xf5, 0xb6, 0xd1, 0x6b, 0x10, 0x43,
	0x27, 0x0d, 0x94, 0xc2, 0x15, 0xd8, 0x36, 0xda, 0x66, 0x8f, 0x3c, 0xd5, 0xbb, 0x26, 0x31, 0xcc,
	0x1e, 0x69, 0x92, 0x16, 0x31, 0x4c, 0x94, 0xc6, 0x18, 0xca, 0xba, 0x61, 0x12, 0x6a, 0x68, 0xcd,
	0x1e, 0xa1, 0xb4, 0x4d, 0xd1, 0x3a, 0x46, 0xb0, 0xd1, 0x7d, 0x66, 0x98, 0xda, 0x53, 0x7f, 0x24,
	0x83, 0xb7, 0xe0, 0x96, 0xd1, 0xee, 0xd5, 0xcf, 0x35, 0xe3, 0x8c, 0xf8, 0x83, 0x59, 0x7c, 0x00,
	0x15, 0xa3, 0xdd, 0x3b, 0xd5, 0x9b, 0x26, 0xa1, 0x3d, 0x4a, 0xba, 0x9d, 0xb6, 0xd1, 0x0d, 0x66,
	0x73, 0x78, 0x0f, 0xb6, 0x74, 0xe3, 0x42, 0x6b, 0xea, 0x8d, 0xde, 0xa9, 0x4e, 0x9a, 0x0d, 0x7f,
	0x22, 0x5f, 0xfb, 0x43, 0x1a, 0x0a, 0xe1, 0x37, 0x27, 0x17, 0xff, 0x5c, 0xa3, 0x8d, 0x27, 0x1a,
	0x25, 0x68, 0x0d, 0xe7, 0x61, 0xfd, 0xa2, 0xa9, 0x19, 0x48, 0x11, 0x2d, 0x62, 0x9e, 0xa3, 0x94,
	0x68, 0xd5, 0x35, 0x03, 0xa5, 0x71, 0x01, 0x32, 0x17, 0x4f, 0x79, 0x73, 0x9d, 0x37, 0x1b, 0x8f,
	0x5b, 0xad, 0x67, 0x28, 0x83, 0x73, 0x90, 0xd6, 0x4f, 0x4f, 0x50, 0x16, 0x17, 0x21, 0xd7, 0xd2,
	0xea, 0x62, 0x7d, 0x2e, 0xe8, 0x98, 0x5a, 0x07, 0xe5, 0x31, 0x40, 0xf6, 0x84, 0xea, 0x8d, 0x33,
	0x82, 0x0a, 0x9c, 0xee, 0xa4, 0x6d, 0x34, 0x10, 0xf0, 0x96, 0x49, 0xb4, 0x16, 0x2a, 0x72, 0x36,
	0xbd, 0xd3, 0xd6, 0x4f, 0xd0, 0x06, 0x87, 0xea, 0x9d, 0x87, 0xa6, 0xd1, 0x44, 0x25, 0x0e, 0xd0,
	0x3b, 0x7a, 0x07, 0x95, 0xf9, 0x1e, 0x5d, 0xdd, 0x44, 0xb7, 0xa4, 0x08, 0x7c, 0x07, 0xc4, 0xc7,
	0xce, 0x28, 0x41, 0x9b, 0x7c, 0xc9, 0x19, 0x25, 0x7c, 0x27, 0xcc, 0xdb, 0x84, 0x76, 0x3b, 0x9a,
	0x81, 0xb6, 0x7c, 0x2a, 0x8e, 0xd9, 0xc6, 0x25, 0x9e, 0xb7, 0x3c, 0xf4, 0x61, 0x3b, 0x7e, 0xd7,
	0x47, 0xee, 0x72, 0xaa, 0x0b, 0x53, 0x47, 0x7b, 0x9c, 0xde, 0x68, 0xb6, 0xda, 0x06, 0xaa, 0xe0,
	0x32, 0x00, 0x97, 0xae, 0xd7, 0x6d, 0x6a, 0x17, 0x04, 0xed, 0xf3, 0x3e, 0x97, 0xdb, 0xef, 0x57,
	0xf9, 0x21, 0x49, 0x9d, 0xfc, 0x91, 0xdb, 0x72, 0x3f, 0xa1, 0xfe, 0x81, 0xdf, 0xe6, 0x9b, 0xdd,
	0x11, 0xf2, 0x11, 0x83, 0x5c, 0x10, 0xf4, 0x9e, 0xd8, 0x89, 0x9e, 0xa2, 0xbb, 0x7c, 0xb0, 0xa5,
	0xd5, 0xbb, 0xa4, 0x8e, 0x0e, 0xb9, 0x34, 0x06, 0x31, 0x1b, 0xe4, 0xa2, 0xab, 0xb7, 0xd0, 0xfb,
	0x5c, 0x08, 0xda, 0x32, 0x88, 0x89, 0xd4, 0x5a, 0x17, 0x36, 0xf8, 0x51, 0xf1, 0x27, 0x9b, 0xd9,
	0x9e, 0xcb, 0x2d, 0x62, 0x68, 0x2d, 0x7e, 0x52, 0x45, 0xc8, 0x69, 0x8d, 0x06, 0x25, 0xdd, 0x2e,
	0x52, 0xb8, 0x6c, 0x3c, 0x64, 0xf9, 0x7d, 0x71, 0x64, 0xe6, 0xb3, 0x0e, 0x41, 0x69, 0xbe, 0x5f,
	0xcb, 0x7c, 0x2c, 0x0f, 0x4c, 0x37, 0x1a, 0xe4, 0x29, 0xca, 0xd4, 0xce, 0xa1, 0x24, 0x12, 0xe1,
	0x90, 0xf5, 0x16, 0x14, 0x1b, 0xa4, 0x6b, 0xea, 0x86, 0x66, 0xea, 0x6d, 0x43, 0x92, 0x9f, 0x69,
	0x26, 0x79, 0xa2, 0x3d, 0x43, 0x8a, 0x90, 0x94, 0x98, 0x54, 0xaf, 0xa3, 0x94, 0xb0, 0x1b, 0xf7,
	0xd6, 0x53, 0xad, 0x4e, 0x50, 0xba, 0x76, 0xc0, 0xb5, 0x14, 0x51, 0x58, 0x1c, 0xd5, 0xc5, 0x27,
	0xd2, 0x85, 0xf4, 0xce, 0xc5, 0x43, 0xa4, 0xd4, 0x3e, 0x85, 0x9d, 0xc4, 0x24, 0x8b, 0x33, 0x76,
	0x4d, 0xcd, 0xd4, 0xeb, 0x12, 0xde, 0x38, 0xaf, 0x77, 0xa4, 0xc7, 0x35, 0x8f, 0xcd, 0x0e, 0x4a,
	0xd5, 0xbe, 0x0b, 0x95, 0x55, 0xa9, 0x0b, 0xbf, 0x76, 0xe7, 0x4f, 0xd0, 0x1a, 0xe7, 0xa0, 0x9a,
	0xd1, 0x68, 0xb7, 0x90, 0x82, 0x37, 0xa1, 0x24, 0xf9, 0x7a, 0xfe, 0x50, 0x8a, 0x5b, 0xa4, 0x43,
	0x49, 0x83, 0x9c, 0xea, 0x06, 0x69, 0xa0, 0x74, 0x8d, 0x00, 0x0a, 0xee, 0x75, 0xa8, 0xb6, 0x38,
	0x23, 0x61, 0xa7, 0x35, 0xe9, 0x10, 0x73, 0x83, 0x4a, 0xef, 0xe5, 0x7d, 0x94, 0xe2, 0xa6, 0xe3,
	0xf4, 0x5c, 0xe1, 0x1f, 0x41, 0x29, 0x16, 0xea, 0xf9, 0x3a, 0x7e, 0xdf, 0x35, 0x83, 0xdf, 0xe6,
	0x35, 0xe1, 0x3f, 0x6d, 0x8d, 0x72, 0x75, 0xe4, 0xaa, 0x26, 0x91, 0x56, 0xa3, 0x44, 0xab, 0x9f,
	0x6b, 0x27, 0x4d, 0x7e, 0x26, 0xfc, 0x10, 0xdb, 0x06, 0x41, 0x19, 0x2e, 0xa5, 0x6e, 0xd4, 0xdb,
	0xad, 0x4e, 0x93, 0x98, 0x04, 0x65, 0xc5, 0xad, 0x22, 0x4d, 0xed, 0x19, 0xca, 0xf1, 0x66, 0x87,
	0xb6, 0x4f, 0x88, 0xbc, 0x3d, 0xa7, 0x9a, 0xde, 0x24, 0x0d, 0x54, 0x38, 0xfe, 0x47, 0x01, 0x76,
	0x8c, 0xc9, 0x80, 0xd5, 0x65, 0x55, 0x7d, 0xc4, 0x1c, 0x9e, 0x1d, 0x0e, 0xfb, 0x0c, 0xeb, 0x00,
	0xf3, 0xaa, 0x38, 0x8e, 0xbc, 0xaa, 0x4b, 0x55, 0xf6, 0xea, 0x41, 0xf2, 0xa4, 0x7c, 0xee, 0xd4,
	0x35, 0x4e, 0x35, 0xaf, 0x1a, 0x47, 0xa9, 0x96, 0x0a, 0xd3, 0x51, 0xaa, 0xe5, 0x42, 0xb3, 0xa4,
	0x9a, 0x17, 0x7b, 0xa3, 0x54, 0x4b, 0xc5, 0xe2, 0x28, 0xd5, 0x72, 0x7d, 0x58, 0x5d, 0xc3, 0xdf,
	0x81, 0x9c, 0x5f, 0xef, 0xc4, 0x95, 0x55, 0x05, 0xd9, 0xea, 0x7e, 0xc2, 0x4c, 0xc8, 0xd0, 0x84,
	0x62, 0xa4, 0x1a, 0x89, 0x0f, 0x62, 0xd8, 0x85, 0xda, 0x65, 0xf5, 0xce, 0x8a, 0xd9, 0x90, 0xed,
	0x07, 0xc1, 0x0f, 0x8c, 0xc8, 0x17, 0x2c, 0x56, 0x17, 0x4d, 0xbb, 0xfc, 0x85, 0x5c, 0xfd, 0xe0,
	0x5a, 0x4c, 0x94, 0x7f, 0xe9, 0xe3, 0x3f, 0xca, 0xbf, 0xaa, 0xba, 0x10, 0xe5, 0x5f, 0x59, 0x3d,
	0x90, 0xfc, 0x4b, 0x5f, 0xe0, 0x51, 0xfe, 0x55, 0x5f, 0xf8, 0x51, 0xfe, 0x95, 0x9f, 0xf0, 0xea,
	0x1a, 0xae, 0x43, 0x3e, 0xa8, 0x93, 0xe1, 0xfd, 0x95, 0xc5, 0xbc, 0x6a, 0x35, 0x69, 0x2a, 0x24,
	0x69, 0xc3, 0x46, 0xb4, 0x8a, 0x85, 0x97, 0x4e, 0x25, 0x56, 0xf5, 0xaa, 0xbe, 0xb7, 0x6a, 0x7a,
	0xc1, 0x07, 0xc2, 0xaf, 0x8f, 0x83, 0xeb, 0xd2, 0xee, 0x05, 0x1f, 0x58, 0x4c, 0x0c, 0xd4, 0x35,
	0xfc, 0x54, 0x54, 0x33, 0xa3, 0xd9, 0x25, 0x3e, 0x5c, 0x14, 0x61, 0x31, 0x27, 0xad, 0xbe, 0x7f,
	0x0d, 0x22, 0x64, 0x7e, 0x0c, 0xe5, 0x78, 0x36, 0x87, 0xef, 0x2e, 0xba, 0xcd, 0xa2, 0xb4, 0x87,
	0xab, 0x01, 0x21, 0xad, 0x09, 0xe5, 0x78, 0x72, 0x16, 0xa5, 0x4d, 0x4c, 0xe8, 0xaa, 0x6f, 0x03,
	0x48, 0x61, 0xe3, 0xb9, 0x53, 0x94, 0x35, 0x31, 0xdd, 0x8a, 0x0a, 0x9b, 0x9c, 0x76, 0xa9, 0x6b,
	0xc7, 0x77, 0xe1, 0x0e, 0x7f, 0xeb, 0x4e, 0x87, 0x0e, 0xfb, 0xc2, 0x1a, 0x8d, 0x96, 0xde, 0xbc,
	0x93, 0xf4, 0xf7, 0x94, 0xa3, 0xe7, 0x59, 0xf1, 0x67, 0xf1, 0xc1, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x92, 0x8c, 0x3f, 0x6f, 0x1c, 0x00, 0x00,
}
