/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by informer-gen. DO NOT EDIT.

package firewall

import (
	internalinterfaces "informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// FirewallChains returns a FirewallChainInformer.
	FirewallChains() FirewallChainInformer
	// FirewallChainLists returns a FirewallChainListInformer.
	FirewallChainLists() FirewallChainListInformer
	// FirewallRules returns a FirewallRuleInformer.
	FirewallRules() FirewallRuleInformer
	// FirewallRuleLists returns a FirewallRuleListInformer.
	FirewallRuleLists() FirewallRuleListInformer
	// FirewallTables returns a FirewallTableInformer.
	FirewallTables() FirewallTableInformer
	// FirewallTableLists returns a FirewallTableListInformer.
	FirewallTableLists() FirewallTableListInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// FirewallChains returns a FirewallChainInformer.
func (v *version) FirewallChains() FirewallChainInformer {
	return &firewallChainInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallChainLists returns a FirewallChainListInformer.
func (v *version) FirewallChainLists() FirewallChainListInformer {
	return &firewallChainListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallRules returns a FirewallRuleInformer.
func (v *version) FirewallRules() FirewallRuleInformer {
	return &firewallRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallRuleLists returns a FirewallRuleListInformer.
func (v *version) FirewallRuleLists() FirewallRuleListInformer {
	return &firewallRuleListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallTables returns a FirewallTableInformer.
func (v *version) FirewallTables() FirewallTableInformer {
	return &firewallTableInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallTableLists returns a FirewallTableListInformer.
func (v *version) FirewallTableLists() FirewallTableListInformer {
	return &firewallTableListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
