/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	internalversion "github.com/fire833/morfic/pkg/client/clientset/internalversion/typed/net/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNet struct {
	*testing.Fake
}

func (c *FakeNet) Addresses(namespace string) internalversion.AddressInterface {
	return &FakeAddresses{c, namespace}
}

func (c *FakeNet) AddressLists(namespace string) internalversion.AddressListInterface {
	return &FakeAddressLists{c, namespace}
}

func (c *FakeNet) Links(namespace string) internalversion.LinkInterface {
	return &FakeLinks{c, namespace}
}

func (c *FakeNet) LinkLists(namespace string) internalversion.LinkListInterface {
	return &FakeLinkLists{c, namespace}
}

func (c *FakeNet) Neighbors(namespace string) internalversion.NeighborInterface {
	return &FakeNeighbors{c, namespace}
}

func (c *FakeNet) NeighborLists(namespace string) internalversion.NeighborListInterface {
	return &FakeNeighborLists{c, namespace}
}

func (c *FakeNet) Routes(namespace string) internalversion.RouteInterface {
	return &FakeRoutes{c, namespace}
}

func (c *FakeNet) RouteTables(namespace string) internalversion.RouteTableInterface {
	return &FakeRouteTables{c, namespace}
}

func (c *FakeNet) RouteTableLists(namespace string) internalversion.RouteTableListInterface {
	return &FakeRouteTableLists{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNet) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
