/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	net "github.com/fire833/morfic/pkg/apis/net"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNeighbors implements NeighborInterface
type FakeNeighbors struct {
	Fake *FakeNet
	ns   string
}

var neighborsResource = schema.GroupVersionResource{Group: "net.morfic.io", Version: "", Resource: "neighbors"}

var neighborsKind = schema.GroupVersionKind{Group: "net.morfic.io", Version: "", Kind: "Neighbor"}

// Get takes name of the neighbor, and returns the corresponding neighbor object, and an error if there is any.
func (c *FakeNeighbors) Get(ctx context.Context, name string, options v1.GetOptions) (result *net.Neighbor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(neighborsResource, c.ns, name), &net.Neighbor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*net.Neighbor), err
}

// List takes label and field selectors, and returns the list of Neighbors that match those selectors.
func (c *FakeNeighbors) List(ctx context.Context, opts v1.ListOptions) (result *net.NeighborList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(neighborsResource, neighborsKind, c.ns, opts), &net.NeighborList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &net.NeighborList{ListMeta: obj.(*net.NeighborList).ListMeta}
	for _, item := range obj.(*net.NeighborList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested neighbors.
func (c *FakeNeighbors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(neighborsResource, c.ns, opts))

}

// Create takes the representation of a neighbor and creates it.  Returns the server's representation of the neighbor, and an error, if there is any.
func (c *FakeNeighbors) Create(ctx context.Context, neighbor *net.Neighbor, opts v1.CreateOptions) (result *net.Neighbor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(neighborsResource, c.ns, neighbor), &net.Neighbor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*net.Neighbor), err
}

// Update takes the representation of a neighbor and updates it. Returns the server's representation of the neighbor, and an error, if there is any.
func (c *FakeNeighbors) Update(ctx context.Context, neighbor *net.Neighbor, opts v1.UpdateOptions) (result *net.Neighbor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(neighborsResource, c.ns, neighbor), &net.Neighbor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*net.Neighbor), err
}

// Delete takes name of the neighbor and deletes it. Returns an error if one occurs.
func (c *FakeNeighbors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(neighborsResource, c.ns, name, opts), &net.Neighbor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNeighbors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(neighborsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &net.NeighborList{})
	return err
}

// Patch applies the patch and returns the patched neighbor.
func (c *FakeNeighbors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *net.Neighbor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(neighborsResource, c.ns, name, pt, data, subresources...), &net.Neighbor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*net.Neighbor), err
}
