//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
// Code generated by deepcopy-gen. DO NOT EDIT.

package vpn

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2TPTunnelConfig) DeepCopyInto(out *L2TPTunnelConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2TPTunnelConfig.
func (in *L2TPTunnelConfig) DeepCopy() *L2TPTunnelConfig {
	if in == nil {
		return nil
	}
	out := new(L2TPTunnelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenVPNTunnelConfig) DeepCopyInto(out *OpenVPNTunnelConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenVPNTunnelConfig.
func (in *OpenVPNTunnelConfig) DeepCopy() *OpenVPNTunnelConfig {
	if in == nil {
		return nil
	}
	out := new(OpenVPNTunnelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnel) DeepCopyInto(out *VPNTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnel.
func (in *VPNTunnel) DeepCopy() *VPNTunnel {
	if in == nil {
		return nil
	}
	out := new(VPNTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPNTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnelList) DeepCopyInto(out *VPNTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPNTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnelList.
func (in *VPNTunnelList) DeepCopy() *VPNTunnelList {
	if in == nil {
		return nil
	}
	out := new(VPNTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPNTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnelSpec) DeepCopyInto(out *VPNTunnelSpec) {
	*out = *in
	out.Wireguard = in.Wireguard
	out.OpenVPN = in.OpenVPN
	out.L2TP = in.L2TP
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnelSpec.
func (in *VPNTunnelSpec) DeepCopy() *VPNTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(VPNTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnelStatus) DeepCopyInto(out *VPNTunnelStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnelStatus.
func (in *VPNTunnelStatus) DeepCopy() *VPNTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(VPNTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardTunnelConfig) DeepCopyInto(out *WireguardTunnelConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardTunnelConfig.
func (in *WireguardTunnelConfig) DeepCopy() *WireguardTunnelConfig {
	if in == nil {
		return nil
	}
	out := new(WireguardTunnelConfig)
	in.DeepCopyInto(out)
	return out
}
