/*
*	Copyright (C) 2022  Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	dns "github.com/fire833/morfic/pkg/apis/dns"
	scheme "github.com/fire833/morfic/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSRecordsGetter has a method to return a DNSRecordInterface.
// A group's client should implement this interface.
type DNSRecordsGetter interface {
	DNSRecords(namespace string) DNSRecordInterface
}

// DNSRecordInterface has methods to work with DNSRecord resources.
type DNSRecordInterface interface {
	Create(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.CreateOptions) (*dns.DNSRecord, error)
	Update(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.UpdateOptions) (*dns.DNSRecord, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*dns.DNSRecord, error)
	List(ctx context.Context, opts v1.ListOptions) (*dns.DNSRecordList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dns.DNSRecord, err error)
	DNSRecordExpansion
}

// dNSRecords implements DNSRecordInterface
type dNSRecords struct {
	client rest.Interface
	ns     string
}

// newDNSRecords returns a DNSRecords
func newDNSRecords(c *DnsClient, namespace string) *dNSRecords {
	return &dNSRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dNSRecord, and returns the corresponding dNSRecord object, and an error if there is any.
func (c *dNSRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *dns.DNSRecord, err error) {
	result = &dns.DNSRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSRecords that match those selectors.
func (c *dNSRecords) List(ctx context.Context, opts v1.ListOptions) (result *dns.DNSRecordList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &dns.DNSRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSRecords.
func (c *dNSRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dNSRecord and creates it.  Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *dNSRecords) Create(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.CreateOptions) (result *dns.DNSRecord, err error) {
	result = &dns.DNSRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSRecord).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dNSRecord and updates it. Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *dNSRecords) Update(ctx context.Context, dNSRecord *dns.DNSRecord, opts v1.UpdateOptions) (result *dns.DNSRecord, err error) {
	result = &dns.DNSRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(dNSRecord.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSRecord).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dNSRecord and deletes it. Returns an error if one occurs.
func (c *dNSRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dNSRecord.
func (c *dNSRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dns.DNSRecord, err error) {
	result = &dns.DNSRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
