name: unit-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-all:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: go setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: setup go environment
      run: |
        go mod vendor

    - name: run unit tests
      run: |
        go test -v ./pkg/...
        go test -v ./cmd/...
        go test -v ./test/...
